// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/sql/sql.proto

package org.mojolang.mojo.db.sql;

/**
 * Protobuf type {@code mojo.db.sql.BinaryExpr}
 */
public final class BinaryExpr extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.db.sql.BinaryExpr)
    BinaryExprOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BinaryExpr.newBuilder() to construct.
  private BinaryExpr(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BinaryExpr() {
    operator_ = 0;
    operatorSymbol_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BinaryExpr();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BinaryExpr(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.mojolang.mojo.lang.Position.Builder subBuilder = null;
            if (startPosition_ != null) {
              subBuilder = startPosition_.toBuilder();
            }
            startPosition_ = input.readMessage(org.mojolang.mojo.lang.Position.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startPosition_);
              startPosition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.mojolang.mojo.lang.Position.Builder subBuilder = null;
            if (endPosition_ != null) {
              subBuilder = endPosition_.toBuilder();
            }
            endPosition_ = input.readMessage(org.mojolang.mojo.lang.Position.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(endPosition_);
              endPosition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            kind_ = input.readInt32();
            break;
          }
          case 40: {

            implicit_ = input.readBool();
            break;
          }
          case 80: {
            int rawValue = input.readEnum();

            operator_ = rawValue;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            operatorSymbol_ = s;
            break;
          }
          case 96: {

            operatorPrecedence_ = input.readInt32();
            break;
          }
          case 122: {
            org.mojolang.mojo.db.sql.Expression.Builder subBuilder = null;
            if (leftArgument_ != null) {
              subBuilder = leftArgument_.toBuilder();
            }
            leftArgument_ = input.readMessage(org.mojolang.mojo.db.sql.Expression.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(leftArgument_);
              leftArgument_ = subBuilder.buildPartial();
            }

            break;
          }
          case 130: {
            org.mojolang.mojo.db.sql.Expression.Builder subBuilder = null;
            if (rightArgument_ != null) {
              subBuilder = rightArgument_.toBuilder();
            }
            rightArgument_ = input.readMessage(org.mojolang.mojo.db.sql.Expression.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(rightArgument_);
              rightArgument_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_BinaryExpr_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_BinaryExpr_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.db.sql.BinaryExpr.class, org.mojolang.mojo.db.sql.BinaryExpr.Builder.class);
  }

  /**
   * Protobuf enum {@code mojo.db.sql.BinaryExpr.Operator}
   */
  public enum Operator
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OPERATOR_UNSPECIFIED = 0;</code>
     */
    OPERATOR_UNSPECIFIED(0),
    /**
     * <code>OPERATOR_PLUS = 1;</code>
     */
    OPERATOR_PLUS(1),
    /**
     * <code>OPERATOR_MINUS = 2;</code>
     */
    OPERATOR_MINUS(2),
    /**
     * <code>OPERATOR_MUL = 3;</code>
     */
    OPERATOR_MUL(3),
    /**
     * <code>OPERATOR_DIV = 4;</code>
     */
    OPERATOR_DIV(4),
    /**
     * <code>OPERATOR_MOD = 5;</code>
     */
    OPERATOR_MOD(5),
    /**
     * <code>OPERATOR_LT = 10;</code>
     */
    OPERATOR_LT(10),
    /**
     * <code>OPERATOR_GT = 11;</code>
     */
    OPERATOR_GT(11),
    /**
     * <code>OPERATOR_LTE = 12;</code>
     */
    OPERATOR_LTE(12),
    /**
     * <code>OPERATOR_GTE = 13;</code>
     */
    OPERATOR_GTE(13),
    /**
     * <code>OPERATOR_EQUAL = 14;</code>
     */
    OPERATOR_EQUAL(14),
    /**
     * <code>OPERATOR_NOT_EQUAL = 15;</code>
     */
    OPERATOR_NOT_EQUAL(15),
    /**
     * <code>OPERATOR_AND = 20;</code>
     */
    OPERATOR_AND(20),
    /**
     * <code>OPERATOR_OR = 21;</code>
     */
    OPERATOR_OR(21),
    /**
     * <code>OPERATOR_BIT_AND = 25;</code>
     */
    OPERATOR_BIT_AND(25),
    /**
     * <code>OPERATOR_BIT_OR = 26;</code>
     */
    OPERATOR_BIT_OR(26),
    /**
     * <code>OPERATOR_BIT_XOR = 27;</code>
     */
    OPERATOR_BIT_XOR(27),
    /**
     * <code>OPERATOR_CONCAT = 30;</code>
     */
    OPERATOR_CONCAT(30),
    /**
     * <code>OPERATOR_EXTENDED = 99;</code>
     */
    OPERATOR_EXTENDED(99),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OPERATOR_UNSPECIFIED = 0;</code>
     */
    public static final int OPERATOR_UNSPECIFIED_VALUE = 0;
    /**
     * <code>OPERATOR_PLUS = 1;</code>
     */
    public static final int OPERATOR_PLUS_VALUE = 1;
    /**
     * <code>OPERATOR_MINUS = 2;</code>
     */
    public static final int OPERATOR_MINUS_VALUE = 2;
    /**
     * <code>OPERATOR_MUL = 3;</code>
     */
    public static final int OPERATOR_MUL_VALUE = 3;
    /**
     * <code>OPERATOR_DIV = 4;</code>
     */
    public static final int OPERATOR_DIV_VALUE = 4;
    /**
     * <code>OPERATOR_MOD = 5;</code>
     */
    public static final int OPERATOR_MOD_VALUE = 5;
    /**
     * <code>OPERATOR_LT = 10;</code>
     */
    public static final int OPERATOR_LT_VALUE = 10;
    /**
     * <code>OPERATOR_GT = 11;</code>
     */
    public static final int OPERATOR_GT_VALUE = 11;
    /**
     * <code>OPERATOR_LTE = 12;</code>
     */
    public static final int OPERATOR_LTE_VALUE = 12;
    /**
     * <code>OPERATOR_GTE = 13;</code>
     */
    public static final int OPERATOR_GTE_VALUE = 13;
    /**
     * <code>OPERATOR_EQUAL = 14;</code>
     */
    public static final int OPERATOR_EQUAL_VALUE = 14;
    /**
     * <code>OPERATOR_NOT_EQUAL = 15;</code>
     */
    public static final int OPERATOR_NOT_EQUAL_VALUE = 15;
    /**
     * <code>OPERATOR_AND = 20;</code>
     */
    public static final int OPERATOR_AND_VALUE = 20;
    /**
     * <code>OPERATOR_OR = 21;</code>
     */
    public static final int OPERATOR_OR_VALUE = 21;
    /**
     * <code>OPERATOR_BIT_AND = 25;</code>
     */
    public static final int OPERATOR_BIT_AND_VALUE = 25;
    /**
     * <code>OPERATOR_BIT_OR = 26;</code>
     */
    public static final int OPERATOR_BIT_OR_VALUE = 26;
    /**
     * <code>OPERATOR_BIT_XOR = 27;</code>
     */
    public static final int OPERATOR_BIT_XOR_VALUE = 27;
    /**
     * <code>OPERATOR_CONCAT = 30;</code>
     */
    public static final int OPERATOR_CONCAT_VALUE = 30;
    /**
     * <code>OPERATOR_EXTENDED = 99;</code>
     */
    public static final int OPERATOR_EXTENDED_VALUE = 99;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Operator valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Operator forNumber(int value) {
      switch (value) {
        case 0: return OPERATOR_UNSPECIFIED;
        case 1: return OPERATOR_PLUS;
        case 2: return OPERATOR_MINUS;
        case 3: return OPERATOR_MUL;
        case 4: return OPERATOR_DIV;
        case 5: return OPERATOR_MOD;
        case 10: return OPERATOR_LT;
        case 11: return OPERATOR_GT;
        case 12: return OPERATOR_LTE;
        case 13: return OPERATOR_GTE;
        case 14: return OPERATOR_EQUAL;
        case 15: return OPERATOR_NOT_EQUAL;
        case 20: return OPERATOR_AND;
        case 21: return OPERATOR_OR;
        case 25: return OPERATOR_BIT_AND;
        case 26: return OPERATOR_BIT_OR;
        case 27: return OPERATOR_BIT_XOR;
        case 30: return OPERATOR_CONCAT;
        case 99: return OPERATOR_EXTENDED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Operator>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Operator> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Operator>() {
            public Operator findValueByNumber(int number) {
              return Operator.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.mojolang.mojo.db.sql.BinaryExpr.getDescriptor().getEnumTypes().get(0);
    }

    private static final Operator[] VALUES = values();

    public static Operator valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Operator(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:mojo.db.sql.BinaryExpr.Operator)
  }

  public static final int START_POSITION_FIELD_NUMBER = 1;
  private org.mojolang.mojo.lang.Position startPosition_;
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return Whether the startPosition field is set.
   */
  @java.lang.Override
  public boolean hasStartPosition() {
    return startPosition_ != null;
  }
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return The startPosition.
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Position getStartPosition() {
    return startPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
  }
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder() {
    return getStartPosition();
  }

  public static final int END_POSITION_FIELD_NUMBER = 2;
  private org.mojolang.mojo.lang.Position endPosition_;
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return Whether the endPosition field is set.
   */
  @java.lang.Override
  public boolean hasEndPosition() {
    return endPosition_ != null;
  }
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return The endPosition.
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Position getEndPosition() {
    return endPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
  }
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder() {
    return getEndPosition();
  }

  public static final int KIND_FIELD_NUMBER = 4;
  private int kind_;
  /**
   * <code>int32 kind = 4;</code>
   * @return The kind.
   */
  @java.lang.Override
  public int getKind() {
    return kind_;
  }

  public static final int IMPLICIT_FIELD_NUMBER = 5;
  private boolean implicit_;
  /**
   * <code>bool implicit = 5;</code>
   * @return The implicit.
   */
  @java.lang.Override
  public boolean getImplicit() {
    return implicit_;
  }

  public static final int OPERATOR_FIELD_NUMBER = 10;
  private int operator_;
  /**
   * <code>.mojo.db.sql.BinaryExpr.Operator operator = 10;</code>
   * @return The enum numeric value on the wire for operator.
   */
  @java.lang.Override public int getOperatorValue() {
    return operator_;
  }
  /**
   * <code>.mojo.db.sql.BinaryExpr.Operator operator = 10;</code>
   * @return The operator.
   */
  @java.lang.Override public org.mojolang.mojo.db.sql.BinaryExpr.Operator getOperator() {
    @SuppressWarnings("deprecation")
    org.mojolang.mojo.db.sql.BinaryExpr.Operator result = org.mojolang.mojo.db.sql.BinaryExpr.Operator.valueOf(operator_);
    return result == null ? org.mojolang.mojo.db.sql.BinaryExpr.Operator.UNRECOGNIZED : result;
  }

  public static final int OPERATOR_SYMBOL_FIELD_NUMBER = 11;
  private volatile java.lang.Object operatorSymbol_;
  /**
   * <code>string operator_symbol = 11;</code>
   * @return The operatorSymbol.
   */
  @java.lang.Override
  public java.lang.String getOperatorSymbol() {
    java.lang.Object ref = operatorSymbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      operatorSymbol_ = s;
      return s;
    }
  }
  /**
   * <code>string operator_symbol = 11;</code>
   * @return The bytes for operatorSymbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOperatorSymbolBytes() {
    java.lang.Object ref = operatorSymbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operatorSymbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATOR_PRECEDENCE_FIELD_NUMBER = 12;
  private int operatorPrecedence_;
  /**
   * <code>int32 operator_precedence = 12;</code>
   * @return The operatorPrecedence.
   */
  @java.lang.Override
  public int getOperatorPrecedence() {
    return operatorPrecedence_;
  }

  public static final int LEFT_ARGUMENT_FIELD_NUMBER = 15;
  private org.mojolang.mojo.db.sql.Expression leftArgument_;
  /**
   * <code>.mojo.db.sql.Expression left_argument = 15;</code>
   * @return Whether the leftArgument field is set.
   */
  @java.lang.Override
  public boolean hasLeftArgument() {
    return leftArgument_ != null;
  }
  /**
   * <code>.mojo.db.sql.Expression left_argument = 15;</code>
   * @return The leftArgument.
   */
  @java.lang.Override
  public org.mojolang.mojo.db.sql.Expression getLeftArgument() {
    return leftArgument_ == null ? org.mojolang.mojo.db.sql.Expression.getDefaultInstance() : leftArgument_;
  }
  /**
   * <code>.mojo.db.sql.Expression left_argument = 15;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.db.sql.ExpressionOrBuilder getLeftArgumentOrBuilder() {
    return getLeftArgument();
  }

  public static final int RIGHT_ARGUMENT_FIELD_NUMBER = 16;
  private org.mojolang.mojo.db.sql.Expression rightArgument_;
  /**
   * <code>.mojo.db.sql.Expression right_argument = 16;</code>
   * @return Whether the rightArgument field is set.
   */
  @java.lang.Override
  public boolean hasRightArgument() {
    return rightArgument_ != null;
  }
  /**
   * <code>.mojo.db.sql.Expression right_argument = 16;</code>
   * @return The rightArgument.
   */
  @java.lang.Override
  public org.mojolang.mojo.db.sql.Expression getRightArgument() {
    return rightArgument_ == null ? org.mojolang.mojo.db.sql.Expression.getDefaultInstance() : rightArgument_;
  }
  /**
   * <code>.mojo.db.sql.Expression right_argument = 16;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.db.sql.ExpressionOrBuilder getRightArgumentOrBuilder() {
    return getRightArgument();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startPosition_ != null) {
      output.writeMessage(1, getStartPosition());
    }
    if (endPosition_ != null) {
      output.writeMessage(2, getEndPosition());
    }
    if (kind_ != 0) {
      output.writeInt32(4, kind_);
    }
    if (implicit_ != false) {
      output.writeBool(5, implicit_);
    }
    if (operator_ != org.mojolang.mojo.db.sql.BinaryExpr.Operator.OPERATOR_UNSPECIFIED.getNumber()) {
      output.writeEnum(10, operator_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operatorSymbol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, operatorSymbol_);
    }
    if (operatorPrecedence_ != 0) {
      output.writeInt32(12, operatorPrecedence_);
    }
    if (leftArgument_ != null) {
      output.writeMessage(15, getLeftArgument());
    }
    if (rightArgument_ != null) {
      output.writeMessage(16, getRightArgument());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startPosition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStartPosition());
    }
    if (endPosition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEndPosition());
    }
    if (kind_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, kind_);
    }
    if (implicit_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, implicit_);
    }
    if (operator_ != org.mojolang.mojo.db.sql.BinaryExpr.Operator.OPERATOR_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, operator_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operatorSymbol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, operatorSymbol_);
    }
    if (operatorPrecedence_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, operatorPrecedence_);
    }
    if (leftArgument_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getLeftArgument());
    }
    if (rightArgument_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, getRightArgument());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.db.sql.BinaryExpr)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.db.sql.BinaryExpr other = (org.mojolang.mojo.db.sql.BinaryExpr) obj;

    if (hasStartPosition() != other.hasStartPosition()) return false;
    if (hasStartPosition()) {
      if (!getStartPosition()
          .equals(other.getStartPosition())) return false;
    }
    if (hasEndPosition() != other.hasEndPosition()) return false;
    if (hasEndPosition()) {
      if (!getEndPosition()
          .equals(other.getEndPosition())) return false;
    }
    if (getKind()
        != other.getKind()) return false;
    if (getImplicit()
        != other.getImplicit()) return false;
    if (operator_ != other.operator_) return false;
    if (!getOperatorSymbol()
        .equals(other.getOperatorSymbol())) return false;
    if (getOperatorPrecedence()
        != other.getOperatorPrecedence()) return false;
    if (hasLeftArgument() != other.hasLeftArgument()) return false;
    if (hasLeftArgument()) {
      if (!getLeftArgument()
          .equals(other.getLeftArgument())) return false;
    }
    if (hasRightArgument() != other.hasRightArgument()) return false;
    if (hasRightArgument()) {
      if (!getRightArgument()
          .equals(other.getRightArgument())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartPosition()) {
      hash = (37 * hash) + START_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getStartPosition().hashCode();
    }
    if (hasEndPosition()) {
      hash = (37 * hash) + END_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getEndPosition().hashCode();
    }
    hash = (37 * hash) + KIND_FIELD_NUMBER;
    hash = (53 * hash) + getKind();
    hash = (37 * hash) + IMPLICIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getImplicit());
    hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
    hash = (53 * hash) + operator_;
    hash = (37 * hash) + OPERATOR_SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getOperatorSymbol().hashCode();
    hash = (37 * hash) + OPERATOR_PRECEDENCE_FIELD_NUMBER;
    hash = (53 * hash) + getOperatorPrecedence();
    if (hasLeftArgument()) {
      hash = (37 * hash) + LEFT_ARGUMENT_FIELD_NUMBER;
      hash = (53 * hash) + getLeftArgument().hashCode();
    }
    if (hasRightArgument()) {
      hash = (37 * hash) + RIGHT_ARGUMENT_FIELD_NUMBER;
      hash = (53 * hash) + getRightArgument().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.db.sql.BinaryExpr parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.db.sql.BinaryExpr parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.db.sql.BinaryExpr parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.db.sql.BinaryExpr parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.db.sql.BinaryExpr parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.db.sql.BinaryExpr parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.db.sql.BinaryExpr parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.db.sql.BinaryExpr parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.db.sql.BinaryExpr parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.db.sql.BinaryExpr parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.db.sql.BinaryExpr parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.db.sql.BinaryExpr parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.db.sql.BinaryExpr prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.db.sql.BinaryExpr}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.db.sql.BinaryExpr)
      org.mojolang.mojo.db.sql.BinaryExprOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_BinaryExpr_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_BinaryExpr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.db.sql.BinaryExpr.class, org.mojolang.mojo.db.sql.BinaryExpr.Builder.class);
    }

    // Construct using org.mojolang.mojo.db.sql.BinaryExpr.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (startPositionBuilder_ == null) {
        startPosition_ = null;
      } else {
        startPosition_ = null;
        startPositionBuilder_ = null;
      }
      if (endPositionBuilder_ == null) {
        endPosition_ = null;
      } else {
        endPosition_ = null;
        endPositionBuilder_ = null;
      }
      kind_ = 0;

      implicit_ = false;

      operator_ = 0;

      operatorSymbol_ = "";

      operatorPrecedence_ = 0;

      if (leftArgumentBuilder_ == null) {
        leftArgument_ = null;
      } else {
        leftArgument_ = null;
        leftArgumentBuilder_ = null;
      }
      if (rightArgumentBuilder_ == null) {
        rightArgument_ = null;
      } else {
        rightArgument_ = null;
        rightArgumentBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_BinaryExpr_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.db.sql.BinaryExpr getDefaultInstanceForType() {
      return org.mojolang.mojo.db.sql.BinaryExpr.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.db.sql.BinaryExpr build() {
      org.mojolang.mojo.db.sql.BinaryExpr result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.db.sql.BinaryExpr buildPartial() {
      org.mojolang.mojo.db.sql.BinaryExpr result = new org.mojolang.mojo.db.sql.BinaryExpr(this);
      if (startPositionBuilder_ == null) {
        result.startPosition_ = startPosition_;
      } else {
        result.startPosition_ = startPositionBuilder_.build();
      }
      if (endPositionBuilder_ == null) {
        result.endPosition_ = endPosition_;
      } else {
        result.endPosition_ = endPositionBuilder_.build();
      }
      result.kind_ = kind_;
      result.implicit_ = implicit_;
      result.operator_ = operator_;
      result.operatorSymbol_ = operatorSymbol_;
      result.operatorPrecedence_ = operatorPrecedence_;
      if (leftArgumentBuilder_ == null) {
        result.leftArgument_ = leftArgument_;
      } else {
        result.leftArgument_ = leftArgumentBuilder_.build();
      }
      if (rightArgumentBuilder_ == null) {
        result.rightArgument_ = rightArgument_;
      } else {
        result.rightArgument_ = rightArgumentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.db.sql.BinaryExpr) {
        return mergeFrom((org.mojolang.mojo.db.sql.BinaryExpr)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.db.sql.BinaryExpr other) {
      if (other == org.mojolang.mojo.db.sql.BinaryExpr.getDefaultInstance()) return this;
      if (other.hasStartPosition()) {
        mergeStartPosition(other.getStartPosition());
      }
      if (other.hasEndPosition()) {
        mergeEndPosition(other.getEndPosition());
      }
      if (other.getKind() != 0) {
        setKind(other.getKind());
      }
      if (other.getImplicit() != false) {
        setImplicit(other.getImplicit());
      }
      if (other.operator_ != 0) {
        setOperatorValue(other.getOperatorValue());
      }
      if (!other.getOperatorSymbol().isEmpty()) {
        operatorSymbol_ = other.operatorSymbol_;
        onChanged();
      }
      if (other.getOperatorPrecedence() != 0) {
        setOperatorPrecedence(other.getOperatorPrecedence());
      }
      if (other.hasLeftArgument()) {
        mergeLeftArgument(other.getLeftArgument());
      }
      if (other.hasRightArgument()) {
        mergeRightArgument(other.getRightArgument());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojolang.mojo.db.sql.BinaryExpr parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojolang.mojo.db.sql.BinaryExpr) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.mojolang.mojo.lang.Position startPosition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> startPositionBuilder_;
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     * @return Whether the startPosition field is set.
     */
    public boolean hasStartPosition() {
      return startPositionBuilder_ != null || startPosition_ != null;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     * @return The startPosition.
     */
    public org.mojolang.mojo.lang.Position getStartPosition() {
      if (startPositionBuilder_ == null) {
        return startPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
      } else {
        return startPositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder setStartPosition(org.mojolang.mojo.lang.Position value) {
      if (startPositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startPosition_ = value;
        onChanged();
      } else {
        startPositionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder setStartPosition(
        org.mojolang.mojo.lang.Position.Builder builderForValue) {
      if (startPositionBuilder_ == null) {
        startPosition_ = builderForValue.build();
        onChanged();
      } else {
        startPositionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder mergeStartPosition(org.mojolang.mojo.lang.Position value) {
      if (startPositionBuilder_ == null) {
        if (startPosition_ != null) {
          startPosition_ =
            org.mojolang.mojo.lang.Position.newBuilder(startPosition_).mergeFrom(value).buildPartial();
        } else {
          startPosition_ = value;
        }
        onChanged();
      } else {
        startPositionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder clearStartPosition() {
      if (startPositionBuilder_ == null) {
        startPosition_ = null;
        onChanged();
      } else {
        startPosition_ = null;
        startPositionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public org.mojolang.mojo.lang.Position.Builder getStartPositionBuilder() {
      
      onChanged();
      return getStartPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder() {
      if (startPositionBuilder_ != null) {
        return startPositionBuilder_.getMessageOrBuilder();
      } else {
        return startPosition_ == null ?
            org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
      }
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> 
        getStartPositionFieldBuilder() {
      if (startPositionBuilder_ == null) {
        startPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder>(
                getStartPosition(),
                getParentForChildren(),
                isClean());
        startPosition_ = null;
      }
      return startPositionBuilder_;
    }

    private org.mojolang.mojo.lang.Position endPosition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> endPositionBuilder_;
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     * @return Whether the endPosition field is set.
     */
    public boolean hasEndPosition() {
      return endPositionBuilder_ != null || endPosition_ != null;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     * @return The endPosition.
     */
    public org.mojolang.mojo.lang.Position getEndPosition() {
      if (endPositionBuilder_ == null) {
        return endPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
      } else {
        return endPositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder setEndPosition(org.mojolang.mojo.lang.Position value) {
      if (endPositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endPosition_ = value;
        onChanged();
      } else {
        endPositionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder setEndPosition(
        org.mojolang.mojo.lang.Position.Builder builderForValue) {
      if (endPositionBuilder_ == null) {
        endPosition_ = builderForValue.build();
        onChanged();
      } else {
        endPositionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder mergeEndPosition(org.mojolang.mojo.lang.Position value) {
      if (endPositionBuilder_ == null) {
        if (endPosition_ != null) {
          endPosition_ =
            org.mojolang.mojo.lang.Position.newBuilder(endPosition_).mergeFrom(value).buildPartial();
        } else {
          endPosition_ = value;
        }
        onChanged();
      } else {
        endPositionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder clearEndPosition() {
      if (endPositionBuilder_ == null) {
        endPosition_ = null;
        onChanged();
      } else {
        endPosition_ = null;
        endPositionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public org.mojolang.mojo.lang.Position.Builder getEndPositionBuilder() {
      
      onChanged();
      return getEndPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder() {
      if (endPositionBuilder_ != null) {
        return endPositionBuilder_.getMessageOrBuilder();
      } else {
        return endPosition_ == null ?
            org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
      }
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> 
        getEndPositionFieldBuilder() {
      if (endPositionBuilder_ == null) {
        endPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder>(
                getEndPosition(),
                getParentForChildren(),
                isClean());
        endPosition_ = null;
      }
      return endPositionBuilder_;
    }

    private int kind_ ;
    /**
     * <code>int32 kind = 4;</code>
     * @return The kind.
     */
    @java.lang.Override
    public int getKind() {
      return kind_;
    }
    /**
     * <code>int32 kind = 4;</code>
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(int value) {
      
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 kind = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      
      kind_ = 0;
      onChanged();
      return this;
    }

    private boolean implicit_ ;
    /**
     * <code>bool implicit = 5;</code>
     * @return The implicit.
     */
    @java.lang.Override
    public boolean getImplicit() {
      return implicit_;
    }
    /**
     * <code>bool implicit = 5;</code>
     * @param value The implicit to set.
     * @return This builder for chaining.
     */
    public Builder setImplicit(boolean value) {
      
      implicit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool implicit = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearImplicit() {
      
      implicit_ = false;
      onChanged();
      return this;
    }

    private int operator_ = 0;
    /**
     * <code>.mojo.db.sql.BinaryExpr.Operator operator = 10;</code>
     * @return The enum numeric value on the wire for operator.
     */
    @java.lang.Override public int getOperatorValue() {
      return operator_;
    }
    /**
     * <code>.mojo.db.sql.BinaryExpr.Operator operator = 10;</code>
     * @param value The enum numeric value on the wire for operator to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorValue(int value) {
      
      operator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.db.sql.BinaryExpr.Operator operator = 10;</code>
     * @return The operator.
     */
    @java.lang.Override
    public org.mojolang.mojo.db.sql.BinaryExpr.Operator getOperator() {
      @SuppressWarnings("deprecation")
      org.mojolang.mojo.db.sql.BinaryExpr.Operator result = org.mojolang.mojo.db.sql.BinaryExpr.Operator.valueOf(operator_);
      return result == null ? org.mojolang.mojo.db.sql.BinaryExpr.Operator.UNRECOGNIZED : result;
    }
    /**
     * <code>.mojo.db.sql.BinaryExpr.Operator operator = 10;</code>
     * @param value The operator to set.
     * @return This builder for chaining.
     */
    public Builder setOperator(org.mojolang.mojo.db.sql.BinaryExpr.Operator value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      operator_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.db.sql.BinaryExpr.Operator operator = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperator() {
      
      operator_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object operatorSymbol_ = "";
    /**
     * <code>string operator_symbol = 11;</code>
     * @return The operatorSymbol.
     */
    public java.lang.String getOperatorSymbol() {
      java.lang.Object ref = operatorSymbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operatorSymbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string operator_symbol = 11;</code>
     * @return The bytes for operatorSymbol.
     */
    public com.google.protobuf.ByteString
        getOperatorSymbolBytes() {
      java.lang.Object ref = operatorSymbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operatorSymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string operator_symbol = 11;</code>
     * @param value The operatorSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorSymbol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      operatorSymbol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string operator_symbol = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperatorSymbol() {
      
      operatorSymbol_ = getDefaultInstance().getOperatorSymbol();
      onChanged();
      return this;
    }
    /**
     * <code>string operator_symbol = 11;</code>
     * @param value The bytes for operatorSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      operatorSymbol_ = value;
      onChanged();
      return this;
    }

    private int operatorPrecedence_ ;
    /**
     * <code>int32 operator_precedence = 12;</code>
     * @return The operatorPrecedence.
     */
    @java.lang.Override
    public int getOperatorPrecedence() {
      return operatorPrecedence_;
    }
    /**
     * <code>int32 operator_precedence = 12;</code>
     * @param value The operatorPrecedence to set.
     * @return This builder for chaining.
     */
    public Builder setOperatorPrecedence(int value) {
      
      operatorPrecedence_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 operator_precedence = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperatorPrecedence() {
      
      operatorPrecedence_ = 0;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.db.sql.Expression leftArgument_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.db.sql.Expression, org.mojolang.mojo.db.sql.Expression.Builder, org.mojolang.mojo.db.sql.ExpressionOrBuilder> leftArgumentBuilder_;
    /**
     * <code>.mojo.db.sql.Expression left_argument = 15;</code>
     * @return Whether the leftArgument field is set.
     */
    public boolean hasLeftArgument() {
      return leftArgumentBuilder_ != null || leftArgument_ != null;
    }
    /**
     * <code>.mojo.db.sql.Expression left_argument = 15;</code>
     * @return The leftArgument.
     */
    public org.mojolang.mojo.db.sql.Expression getLeftArgument() {
      if (leftArgumentBuilder_ == null) {
        return leftArgument_ == null ? org.mojolang.mojo.db.sql.Expression.getDefaultInstance() : leftArgument_;
      } else {
        return leftArgumentBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.db.sql.Expression left_argument = 15;</code>
     */
    public Builder setLeftArgument(org.mojolang.mojo.db.sql.Expression value) {
      if (leftArgumentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        leftArgument_ = value;
        onChanged();
      } else {
        leftArgumentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.Expression left_argument = 15;</code>
     */
    public Builder setLeftArgument(
        org.mojolang.mojo.db.sql.Expression.Builder builderForValue) {
      if (leftArgumentBuilder_ == null) {
        leftArgument_ = builderForValue.build();
        onChanged();
      } else {
        leftArgumentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.Expression left_argument = 15;</code>
     */
    public Builder mergeLeftArgument(org.mojolang.mojo.db.sql.Expression value) {
      if (leftArgumentBuilder_ == null) {
        if (leftArgument_ != null) {
          leftArgument_ =
            org.mojolang.mojo.db.sql.Expression.newBuilder(leftArgument_).mergeFrom(value).buildPartial();
        } else {
          leftArgument_ = value;
        }
        onChanged();
      } else {
        leftArgumentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.Expression left_argument = 15;</code>
     */
    public Builder clearLeftArgument() {
      if (leftArgumentBuilder_ == null) {
        leftArgument_ = null;
        onChanged();
      } else {
        leftArgument_ = null;
        leftArgumentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.Expression left_argument = 15;</code>
     */
    public org.mojolang.mojo.db.sql.Expression.Builder getLeftArgumentBuilder() {
      
      onChanged();
      return getLeftArgumentFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.db.sql.Expression left_argument = 15;</code>
     */
    public org.mojolang.mojo.db.sql.ExpressionOrBuilder getLeftArgumentOrBuilder() {
      if (leftArgumentBuilder_ != null) {
        return leftArgumentBuilder_.getMessageOrBuilder();
      } else {
        return leftArgument_ == null ?
            org.mojolang.mojo.db.sql.Expression.getDefaultInstance() : leftArgument_;
      }
    }
    /**
     * <code>.mojo.db.sql.Expression left_argument = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.db.sql.Expression, org.mojolang.mojo.db.sql.Expression.Builder, org.mojolang.mojo.db.sql.ExpressionOrBuilder> 
        getLeftArgumentFieldBuilder() {
      if (leftArgumentBuilder_ == null) {
        leftArgumentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.db.sql.Expression, org.mojolang.mojo.db.sql.Expression.Builder, org.mojolang.mojo.db.sql.ExpressionOrBuilder>(
                getLeftArgument(),
                getParentForChildren(),
                isClean());
        leftArgument_ = null;
      }
      return leftArgumentBuilder_;
    }

    private org.mojolang.mojo.db.sql.Expression rightArgument_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.db.sql.Expression, org.mojolang.mojo.db.sql.Expression.Builder, org.mojolang.mojo.db.sql.ExpressionOrBuilder> rightArgumentBuilder_;
    /**
     * <code>.mojo.db.sql.Expression right_argument = 16;</code>
     * @return Whether the rightArgument field is set.
     */
    public boolean hasRightArgument() {
      return rightArgumentBuilder_ != null || rightArgument_ != null;
    }
    /**
     * <code>.mojo.db.sql.Expression right_argument = 16;</code>
     * @return The rightArgument.
     */
    public org.mojolang.mojo.db.sql.Expression getRightArgument() {
      if (rightArgumentBuilder_ == null) {
        return rightArgument_ == null ? org.mojolang.mojo.db.sql.Expression.getDefaultInstance() : rightArgument_;
      } else {
        return rightArgumentBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.db.sql.Expression right_argument = 16;</code>
     */
    public Builder setRightArgument(org.mojolang.mojo.db.sql.Expression value) {
      if (rightArgumentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rightArgument_ = value;
        onChanged();
      } else {
        rightArgumentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.Expression right_argument = 16;</code>
     */
    public Builder setRightArgument(
        org.mojolang.mojo.db.sql.Expression.Builder builderForValue) {
      if (rightArgumentBuilder_ == null) {
        rightArgument_ = builderForValue.build();
        onChanged();
      } else {
        rightArgumentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.Expression right_argument = 16;</code>
     */
    public Builder mergeRightArgument(org.mojolang.mojo.db.sql.Expression value) {
      if (rightArgumentBuilder_ == null) {
        if (rightArgument_ != null) {
          rightArgument_ =
            org.mojolang.mojo.db.sql.Expression.newBuilder(rightArgument_).mergeFrom(value).buildPartial();
        } else {
          rightArgument_ = value;
        }
        onChanged();
      } else {
        rightArgumentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.Expression right_argument = 16;</code>
     */
    public Builder clearRightArgument() {
      if (rightArgumentBuilder_ == null) {
        rightArgument_ = null;
        onChanged();
      } else {
        rightArgument_ = null;
        rightArgumentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.Expression right_argument = 16;</code>
     */
    public org.mojolang.mojo.db.sql.Expression.Builder getRightArgumentBuilder() {
      
      onChanged();
      return getRightArgumentFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.db.sql.Expression right_argument = 16;</code>
     */
    public org.mojolang.mojo.db.sql.ExpressionOrBuilder getRightArgumentOrBuilder() {
      if (rightArgumentBuilder_ != null) {
        return rightArgumentBuilder_.getMessageOrBuilder();
      } else {
        return rightArgument_ == null ?
            org.mojolang.mojo.db.sql.Expression.getDefaultInstance() : rightArgument_;
      }
    }
    /**
     * <code>.mojo.db.sql.Expression right_argument = 16;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.db.sql.Expression, org.mojolang.mojo.db.sql.Expression.Builder, org.mojolang.mojo.db.sql.ExpressionOrBuilder> 
        getRightArgumentFieldBuilder() {
      if (rightArgumentBuilder_ == null) {
        rightArgumentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.db.sql.Expression, org.mojolang.mojo.db.sql.Expression.Builder, org.mojolang.mojo.db.sql.ExpressionOrBuilder>(
                getRightArgument(),
                getParentForChildren(),
                isClean());
        rightArgument_ = null;
      }
      return rightArgumentBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.db.sql.BinaryExpr)
  }

  // @@protoc_insertion_point(class_scope:mojo.db.sql.BinaryExpr)
  private static final org.mojolang.mojo.db.sql.BinaryExpr DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.db.sql.BinaryExpr();
  }

  public static org.mojolang.mojo.db.sql.BinaryExpr getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BinaryExpr>
      PARSER = new com.google.protobuf.AbstractParser<BinaryExpr>() {
    @java.lang.Override
    public BinaryExpr parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BinaryExpr(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BinaryExpr> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BinaryExpr> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.db.sql.BinaryExpr getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

