// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/boxed_timestamp.proto

package org.mojo-lang.mojo.db;

public final class BoxedTimestampProto {
  private BoxedTimestampProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_BoxedTimestamp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_BoxedTimestamp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035mojo/db/boxed_timestamp.proto\022\007mojo.db" +
      "\032\024mojo/core/time.proto\"5\n\016BoxedTimestamp" +
      "\022#\n\005value\030\001 \001(\0132\024.mojo.core.TimestampBY\n" +
      "\025org.mojo-lang.mojo.dbB\023BoxedTimestampPr" +
      "otoP\001Z)github.com/mojo-lang/db/go/pkg/mo" +
      "jo/db;dbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.TimeProto.getDescriptor(),
        });
    internal_static_mojo_db_BoxedTimestamp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_db_BoxedTimestamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_BoxedTimestamp_descriptor,
        new java.lang.String[] { "Value", });
    org.mojolang.mojo.core.TimeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
