// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/boxed_timestamp.proto

package org.mojo-lang.mojo.db;

public interface BoxedTimestampOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.db.BoxedTimestamp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mojo.core.Timestamp value = 1;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.mojo.core.Timestamp value = 1;</code>
   * @return The value.
   */
  org.mojolang.mojo.core.Timestamp getValue();
  /**
   * <code>.mojo.core.Timestamp value = 1;</code>
   */
  org.mojolang.mojo.core.TimestampOrBuilder getValueOrBuilder();
}
