// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/sql/column_name_expr.proto

package org.mojo-lang.mojo.db.sql;

public final class ColumnNameExprProto {
  private ColumnNameExprProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_ColumnNameExpr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_ColumnNameExpr_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"mojo/db/sql/column_name_expr.proto\022\013mo" +
      "jo.db.sql\032\024mojo/lang/lang.proto\"\277\001\n\016Colu" +
      "mnNameExpr\022+\n\016start_position\030\001 \001(\0132\023.moj" +
      "o.lang.Position\022)\n\014end_position\030\002 \001(\0132\023." +
      "mojo.lang.Position\022\014\n\004kind\030\004 \001(\005\022\020\n\010impl" +
      "icit\030\005 \001(\010\022\023\n\013schema_name\030\n \001(\t\022\022\n\ntable" +
      "_name\030\013 \001(\t\022\014\n\004name\030\017 \001(\tBb\n\031org.mojo-la" +
      "ng.mojo.db.sqlB\023ColumnNameExprProtoP\001Z.g" +
      "ithub.com/mojo-lang/db/go/pkg/mojo/db/sq" +
      "l;sqlb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.lang.LangProto.getDescriptor(),
        });
    internal_static_mojo_db_sql_ColumnNameExpr_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_db_sql_ColumnNameExpr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_ColumnNameExpr_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "SchemaName", "TableName", "Name", });
    org.mojolang.mojo.lang.LangProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
