// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/sql/sql.proto

package org.mojo-lang.mojo.db.sql;

public interface CompoundSelectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.db.sql.CompoundSelect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return Whether the startPosition field is set.
   */
  boolean hasStartPosition();
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return The startPosition.
   */
  org.mojolang.mojo.lang.Position getStartPosition();
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder();

  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return Whether the endPosition field is set.
   */
  boolean hasEndPosition();
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return The endPosition.
   */
  org.mojolang.mojo.lang.Position getEndPosition();
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder();

  /**
   * <code>int64 kind = 4;</code>
   * @return The kind.
   */
  long getKind();

  /**
   * <code>bool implicit = 5;</code>
   * @return The implicit.
   */
  boolean getImplicit();

  /**
   * <code>.mojo.db.sql.WithClause with = 10;</code>
   * @return Whether the with field is set.
   */
  boolean hasWith();
  /**
   * <code>.mojo.db.sql.WithClause with = 10;</code>
   * @return The with.
   */
  org.mojo-lang.mojo.db.sql.WithClause getWith();
  /**
   * <code>.mojo.db.sql.WithClause with = 10;</code>
   */
  org.mojo-lang.mojo.db.sql.WithClauseOrBuilder getWithOrBuilder();

  /**
   * <code>.mojo.db.sql.SelectClause select_clause = 11;</code>
   * @return Whether the selectClause field is set.
   */
  boolean hasSelectClause();
  /**
   * <code>.mojo.db.sql.SelectClause select_clause = 11;</code>
   * @return The selectClause.
   */
  org.mojo-lang.mojo.db.sql.SelectClause getSelectClause();
  /**
   * <code>.mojo.db.sql.SelectClause select_clause = 11;</code>
   */
  org.mojo-lang.mojo.db.sql.SelectClauseOrBuilder getSelectClauseOrBuilder();

  /**
   * <code>.mojo.db.sql.CompoundSelect compound_select = 12;</code>
   * @return Whether the compoundSelect field is set.
   */
  boolean hasCompoundSelect();
  /**
   * <code>.mojo.db.sql.CompoundSelect compound_select = 12;</code>
   * @return The compoundSelect.
   */
  org.mojo-lang.mojo.db.sql.CompoundSelect getCompoundSelect();
  /**
   * <code>.mojo.db.sql.CompoundSelect compound_select = 12;</code>
   */
  org.mojo-lang.mojo.db.sql.CompoundSelectOrBuilder getCompoundSelectOrBuilder();

  /**
   * <code>.mojo.db.sql.FromClause from = 13;</code>
   * @return Whether the from field is set.
   */
  boolean hasFrom();
  /**
   * <code>.mojo.db.sql.FromClause from = 13;</code>
   * @return The from.
   */
  org.mojo-lang.mojo.db.sql.FromClause getFrom();
  /**
   * <code>.mojo.db.sql.FromClause from = 13;</code>
   */
  org.mojo-lang.mojo.db.sql.FromClauseOrBuilder getFromOrBuilder();

  /**
   * <code>.mojo.db.sql.WhereClause where = 14;</code>
   * @return Whether the where field is set.
   */
  boolean hasWhere();
  /**
   * <code>.mojo.db.sql.WhereClause where = 14;</code>
   * @return The where.
   */
  org.mojo-lang.mojo.db.sql.WhereClause getWhere();
  /**
   * <code>.mojo.db.sql.WhereClause where = 14;</code>
   */
  org.mojo-lang.mojo.db.sql.WhereClauseOrBuilder getWhereOrBuilder();

  /**
   * <code>.mojo.db.sql.GroupByClause group_by = 15;</code>
   * @return Whether the groupBy field is set.
   */
  boolean hasGroupBy();
  /**
   * <code>.mojo.db.sql.GroupByClause group_by = 15;</code>
   * @return The groupBy.
   */
  org.mojo-lang.mojo.db.sql.GroupByClause getGroupBy();
  /**
   * <code>.mojo.db.sql.GroupByClause group_by = 15;</code>
   */
  org.mojo-lang.mojo.db.sql.GroupByClauseOrBuilder getGroupByOrBuilder();

  /**
   * <code>.mojo.db.sql.HavingClause having = 16;</code>
   * @return Whether the having field is set.
   */
  boolean hasHaving();
  /**
   * <code>.mojo.db.sql.HavingClause having = 16;</code>
   * @return The having.
   */
  org.mojo-lang.mojo.db.sql.HavingClause getHaving();
  /**
   * <code>.mojo.db.sql.HavingClause having = 16;</code>
   */
  org.mojo-lang.mojo.db.sql.HavingClauseOrBuilder getHavingOrBuilder();

  /**
   * <code>.mojo.db.sql.OrderByClause order_by = 17;</code>
   * @return Whether the orderBy field is set.
   */
  boolean hasOrderBy();
  /**
   * <code>.mojo.db.sql.OrderByClause order_by = 17;</code>
   * @return The orderBy.
   */
  org.mojo-lang.mojo.db.sql.OrderByClause getOrderBy();
  /**
   * <code>.mojo.db.sql.OrderByClause order_by = 17;</code>
   */
  org.mojo-lang.mojo.db.sql.OrderByClauseOrBuilder getOrderByOrBuilder();

  /**
   * <code>.mojo.db.sql.LimitClause limit = 18;</code>
   * @return Whether the limit field is set.
   */
  boolean hasLimit();
  /**
   * <code>.mojo.db.sql.LimitClause limit = 18;</code>
   * @return The limit.
   */
  org.mojo-lang.mojo.db.sql.LimitClause getLimit();
  /**
   * <code>.mojo.db.sql.LimitClause limit = 18;</code>
   */
  org.mojo-lang.mojo.db.sql.LimitClauseOrBuilder getLimitOrBuilder();

  /**
   * <code>.mojo.db.sql.CompoundSelect.Operator operator = 20;</code>
   * @return The enum numeric value on the wire for operator.
   */
  int getOperatorValue();
  /**
   * <code>.mojo.db.sql.CompoundSelect.Operator operator = 20;</code>
   * @return The operator.
   */
  org.mojo-lang.mojo.db.sql.CompoundSelect.Operator getOperator();

  /**
   * <code>.mojo.db.sql.CompoundSelect left = 21;</code>
   * @return Whether the left field is set.
   */
  boolean hasLeft();
  /**
   * <code>.mojo.db.sql.CompoundSelect left = 21;</code>
   * @return The left.
   */
  org.mojo-lang.mojo.db.sql.CompoundSelect getLeft();
  /**
   * <code>.mojo.db.sql.CompoundSelect left = 21;</code>
   */
  org.mojo-lang.mojo.db.sql.CompoundSelectOrBuilder getLeftOrBuilder();

  /**
   * <code>.mojo.db.sql.CompoundSelect right = 22;</code>
   * @return Whether the right field is set.
   */
  boolean hasRight();
  /**
   * <code>.mojo.db.sql.CompoundSelect right = 22;</code>
   * @return The right.
   */
  org.mojo-lang.mojo.db.sql.CompoundSelect getRight();
  /**
   * <code>.mojo.db.sql.CompoundSelect right = 22;</code>
   */
  org.mojo-lang.mojo.db.sql.CompoundSelectOrBuilder getRightOrBuilder();

  public org.mojo-lang.mojo.db.sql.CompoundSelect.SelectCase getSelectCase();
}
