// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/sql/sql.proto

package org.mojo-lang.mojo.db.sql;

public interface ExprColumnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.db.sql.ExprColumn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mojo.db.sql.Expression expr = 1;</code>
   * @return Whether the expr field is set.
   */
  boolean hasExpr();
  /**
   * <code>.mojo.db.sql.Expression expr = 1;</code>
   * @return The expr.
   */
  org.mojo-lang.mojo.db.sql.Expression getExpr();
  /**
   * <code>.mojo.db.sql.Expression expr = 1;</code>
   */
  org.mojo-lang.mojo.db.sql.ExpressionOrBuilder getExprOrBuilder();

  /**
   * <code>string alias = 2;</code>
   * @return The alias.
   */
  java.lang.String getAlias();
  /**
   * <code>string alias = 2;</code>
   * @return The bytes for alias.
   */
  com.google.protobuf.ByteString
      getAliasBytes();
}
