// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/sql/sql.proto

package org.mojo-lang.mojo.db.sql;

public interface ExpressionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.db.sql.Expression)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mojo.lang.NullLiteralExpr null_literal_expr = 1;</code>
   * @return Whether the nullLiteralExpr field is set.
   */
  boolean hasNullLiteralExpr();
  /**
   * <code>.mojo.lang.NullLiteralExpr null_literal_expr = 1;</code>
   * @return The nullLiteralExpr.
   */
  org.mojolang.mojo.lang.NullLiteralExpr getNullLiteralExpr();
  /**
   * <code>.mojo.lang.NullLiteralExpr null_literal_expr = 1;</code>
   */
  org.mojolang.mojo.lang.NullLiteralExprOrBuilder getNullLiteralExprOrBuilder();

  /**
   * <code>.mojo.lang.BoolLiteralExpr bool_literal_expr = 2;</code>
   * @return Whether the boolLiteralExpr field is set.
   */
  boolean hasBoolLiteralExpr();
  /**
   * <code>.mojo.lang.BoolLiteralExpr bool_literal_expr = 2;</code>
   * @return The boolLiteralExpr.
   */
  org.mojolang.mojo.lang.BoolLiteralExpr getBoolLiteralExpr();
  /**
   * <code>.mojo.lang.BoolLiteralExpr bool_literal_expr = 2;</code>
   */
  org.mojolang.mojo.lang.BoolLiteralExprOrBuilder getBoolLiteralExprOrBuilder();

  /**
   * <code>.mojo.lang.IntegerLiteralExpr integer_literal_expr = 3;</code>
   * @return Whether the integerLiteralExpr field is set.
   */
  boolean hasIntegerLiteralExpr();
  /**
   * <code>.mojo.lang.IntegerLiteralExpr integer_literal_expr = 3;</code>
   * @return The integerLiteralExpr.
   */
  org.mojolang.mojo.lang.IntegerLiteralExpr getIntegerLiteralExpr();
  /**
   * <code>.mojo.lang.IntegerLiteralExpr integer_literal_expr = 3;</code>
   */
  org.mojolang.mojo.lang.IntegerLiteralExprOrBuilder getIntegerLiteralExprOrBuilder();

  /**
   * <code>.mojo.lang.FloatLiteralExpr float_literal_expr = 4;</code>
   * @return Whether the floatLiteralExpr field is set.
   */
  boolean hasFloatLiteralExpr();
  /**
   * <code>.mojo.lang.FloatLiteralExpr float_literal_expr = 4;</code>
   * @return The floatLiteralExpr.
   */
  org.mojolang.mojo.lang.FloatLiteralExpr getFloatLiteralExpr();
  /**
   * <code>.mojo.lang.FloatLiteralExpr float_literal_expr = 4;</code>
   */
  org.mojolang.mojo.lang.FloatLiteralExprOrBuilder getFloatLiteralExprOrBuilder();

  /**
   * <code>.mojo.lang.StringLiteralExpr string_literal_expr = 5;</code>
   * @return Whether the stringLiteralExpr field is set.
   */
  boolean hasStringLiteralExpr();
  /**
   * <code>.mojo.lang.StringLiteralExpr string_literal_expr = 5;</code>
   * @return The stringLiteralExpr.
   */
  org.mojolang.mojo.lang.StringLiteralExpr getStringLiteralExpr();
  /**
   * <code>.mojo.lang.StringLiteralExpr string_literal_expr = 5;</code>
   */
  org.mojolang.mojo.lang.StringLiteralExprOrBuilder getStringLiteralExprOrBuilder();

  /**
   * <code>.mojo.db.sql.BlobLiteralExpr blob_literal_expr = 6;</code>
   * @return Whether the blobLiteralExpr field is set.
   */
  boolean hasBlobLiteralExpr();
  /**
   * <code>.mojo.db.sql.BlobLiteralExpr blob_literal_expr = 6;</code>
   * @return The blobLiteralExpr.
   */
  org.mojo-lang.mojo.db.sql.BlobLiteralExpr getBlobLiteralExpr();
  /**
   * <code>.mojo.db.sql.BlobLiteralExpr blob_literal_expr = 6;</code>
   */
  org.mojo-lang.mojo.db.sql.BlobLiteralExprOrBuilder getBlobLiteralExprOrBuilder();

  /**
   * <code>.mojo.db.sql.IdentifierExpr identifier_expr = 7;</code>
   * @return Whether the identifierExpr field is set.
   */
  boolean hasIdentifierExpr();
  /**
   * <code>.mojo.db.sql.IdentifierExpr identifier_expr = 7;</code>
   * @return The identifierExpr.
   */
  org.mojo-lang.mojo.db.sql.IdentifierExpr getIdentifierExpr();
  /**
   * <code>.mojo.db.sql.IdentifierExpr identifier_expr = 7;</code>
   */
  org.mojo-lang.mojo.db.sql.IdentifierExprOrBuilder getIdentifierExprOrBuilder();

  /**
   * <code>.mojo.db.sql.BindParameterExpr bind_parameter_expr = 10;</code>
   * @return Whether the bindParameterExpr field is set.
   */
  boolean hasBindParameterExpr();
  /**
   * <code>.mojo.db.sql.BindParameterExpr bind_parameter_expr = 10;</code>
   * @return The bindParameterExpr.
   */
  org.mojo-lang.mojo.db.sql.BindParameterExpr getBindParameterExpr();
  /**
   * <code>.mojo.db.sql.BindParameterExpr bind_parameter_expr = 10;</code>
   */
  org.mojo-lang.mojo.db.sql.BindParameterExprOrBuilder getBindParameterExprOrBuilder();

  /**
   * <code>.mojo.db.sql.ColumnRefExpr column_ref_expr = 11;</code>
   * @return Whether the columnRefExpr field is set.
   */
  boolean hasColumnRefExpr();
  /**
   * <code>.mojo.db.sql.ColumnRefExpr column_ref_expr = 11;</code>
   * @return The columnRefExpr.
   */
  org.mojo-lang.mojo.db.sql.ColumnRefExpr getColumnRefExpr();
  /**
   * <code>.mojo.db.sql.ColumnRefExpr column_ref_expr = 11;</code>
   */
  org.mojo-lang.mojo.db.sql.ColumnRefExprOrBuilder getColumnRefExprOrBuilder();

  /**
   * <code>.mojo.db.sql.PrefixUnaryExpr prefix_unary_expr = 15;</code>
   * @return Whether the prefixUnaryExpr field is set.
   */
  boolean hasPrefixUnaryExpr();
  /**
   * <code>.mojo.db.sql.PrefixUnaryExpr prefix_unary_expr = 15;</code>
   * @return The prefixUnaryExpr.
   */
  org.mojo-lang.mojo.db.sql.PrefixUnaryExpr getPrefixUnaryExpr();
  /**
   * <code>.mojo.db.sql.PrefixUnaryExpr prefix_unary_expr = 15;</code>
   */
  org.mojo-lang.mojo.db.sql.PrefixUnaryExprOrBuilder getPrefixUnaryExprOrBuilder();

  /**
   * <code>.mojo.db.sql.PostfixUnaryExpr postfix_unary_expr = 16;</code>
   * @return Whether the postfixUnaryExpr field is set.
   */
  boolean hasPostfixUnaryExpr();
  /**
   * <code>.mojo.db.sql.PostfixUnaryExpr postfix_unary_expr = 16;</code>
   * @return The postfixUnaryExpr.
   */
  org.mojo-lang.mojo.db.sql.PostfixUnaryExpr getPostfixUnaryExpr();
  /**
   * <code>.mojo.db.sql.PostfixUnaryExpr postfix_unary_expr = 16;</code>
   */
  org.mojo-lang.mojo.db.sql.PostfixUnaryExprOrBuilder getPostfixUnaryExprOrBuilder();

  /**
   * <code>.mojo.db.sql.BinaryExpr binary_expr = 17;</code>
   * @return Whether the binaryExpr field is set.
   */
  boolean hasBinaryExpr();
  /**
   * <code>.mojo.db.sql.BinaryExpr binary_expr = 17;</code>
   * @return The binaryExpr.
   */
  org.mojo-lang.mojo.db.sql.BinaryExpr getBinaryExpr();
  /**
   * <code>.mojo.db.sql.BinaryExpr binary_expr = 17;</code>
   */
  org.mojo-lang.mojo.db.sql.BinaryExprOrBuilder getBinaryExprOrBuilder();

  /**
   * <code>.mojo.db.sql.BetweenExpr between_expr = 18;</code>
   * @return Whether the betweenExpr field is set.
   */
  boolean hasBetweenExpr();
  /**
   * <code>.mojo.db.sql.BetweenExpr between_expr = 18;</code>
   * @return The betweenExpr.
   */
  org.mojo-lang.mojo.db.sql.BetweenExpr getBetweenExpr();
  /**
   * <code>.mojo.db.sql.BetweenExpr between_expr = 18;</code>
   */
  org.mojo-lang.mojo.db.sql.BetweenExprOrBuilder getBetweenExprOrBuilder();

  /**
   * <code>.mojo.db.sql.InExpr in_expr = 19;</code>
   * @return Whether the inExpr field is set.
   */
  boolean hasInExpr();
  /**
   * <code>.mojo.db.sql.InExpr in_expr = 19;</code>
   * @return The inExpr.
   */
  org.mojo-lang.mojo.db.sql.InExpr getInExpr();
  /**
   * <code>.mojo.db.sql.InExpr in_expr = 19;</code>
   */
  org.mojo-lang.mojo.db.sql.InExprOrBuilder getInExprOrBuilder();

  /**
   * <code>.mojo.db.sql.CaseExpr case_expr = 20;</code>
   * @return Whether the caseExpr field is set.
   */
  boolean hasCaseExpr();
  /**
   * <code>.mojo.db.sql.CaseExpr case_expr = 20;</code>
   * @return The caseExpr.
   */
  org.mojo-lang.mojo.db.sql.CaseExpr getCaseExpr();
  /**
   * <code>.mojo.db.sql.CaseExpr case_expr = 20;</code>
   */
  org.mojo-lang.mojo.db.sql.CaseExprOrBuilder getCaseExprOrBuilder();

  /**
   * <code>.mojo.db.sql.FunctionCallExpr function_call_expr = 21;</code>
   * @return Whether the functionCallExpr field is set.
   */
  boolean hasFunctionCallExpr();
  /**
   * <code>.mojo.db.sql.FunctionCallExpr function_call_expr = 21;</code>
   * @return The functionCallExpr.
   */
  org.mojo-lang.mojo.db.sql.FunctionCallExpr getFunctionCallExpr();
  /**
   * <code>.mojo.db.sql.FunctionCallExpr function_call_expr = 21;</code>
   */
  org.mojo-lang.mojo.db.sql.FunctionCallExprOrBuilder getFunctionCallExprOrBuilder();

  /**
   * <code>.mojo.db.sql.SubqueryExpr subquery_expr = 30;</code>
   * @return Whether the subqueryExpr field is set.
   */
  boolean hasSubqueryExpr();
  /**
   * <code>.mojo.db.sql.SubqueryExpr subquery_expr = 30;</code>
   * @return The subqueryExpr.
   */
  org.mojo-lang.mojo.db.sql.SubqueryExpr getSubqueryExpr();
  /**
   * <code>.mojo.db.sql.SubqueryExpr subquery_expr = 30;</code>
   */
  org.mojo-lang.mojo.db.sql.SubqueryExprOrBuilder getSubqueryExprOrBuilder();

  public org.mojo-lang.mojo.db.sql.Expression.ExpressionCase getExpressionCase();
}
