// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/sql/sql.proto

package org.mojo-lang.mojo.db.sql;

/**
 * Protobuf type {@code mojo.db.sql.OrderByClause}
 */
public final class OrderByClause extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.db.sql.OrderByClause)
    OrderByClauseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderByClause.newBuilder() to construct.
  private OrderByClause(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderByClause() {
    orderings_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OrderByClause();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderByClause(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.mojolang.mojo.lang.Position.Builder subBuilder = null;
            if (startPosition_ != null) {
              subBuilder = startPosition_.toBuilder();
            }
            startPosition_ = input.readMessage(org.mojolang.mojo.lang.Position.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startPosition_);
              startPosition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.mojolang.mojo.lang.Position.Builder subBuilder = null;
            if (endPosition_ != null) {
              subBuilder = endPosition_.toBuilder();
            }
            endPosition_ = input.readMessage(org.mojolang.mojo.lang.Position.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(endPosition_);
              endPosition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            kind_ = input.readInt64();
            break;
          }
          case 40: {

            implicit_ = input.readBool();
            break;
          }
          case 82: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              orderings_ = new java.util.ArrayList<org.mojo-lang.mojo.db.sql.Ordering>();
              mutable_bitField0_ |= 0x00000001;
            }
            orderings_.add(
                input.readMessage(org.mojo-lang.mojo.db.sql.Ordering.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        orderings_ = java.util.Collections.unmodifiableList(orderings_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojo-lang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_OrderByClause_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojo-lang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_OrderByClause_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojo-lang.mojo.db.sql.OrderByClause.class, org.mojo-lang.mojo.db.sql.OrderByClause.Builder.class);
  }

  public static final int START_POSITION_FIELD_NUMBER = 1;
  private org.mojolang.mojo.lang.Position startPosition_;
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return Whether the startPosition field is set.
   */
  @java.lang.Override
  public boolean hasStartPosition() {
    return startPosition_ != null;
  }
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return The startPosition.
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Position getStartPosition() {
    return startPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
  }
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder() {
    return getStartPosition();
  }

  public static final int END_POSITION_FIELD_NUMBER = 2;
  private org.mojolang.mojo.lang.Position endPosition_;
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return Whether the endPosition field is set.
   */
  @java.lang.Override
  public boolean hasEndPosition() {
    return endPosition_ != null;
  }
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return The endPosition.
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Position getEndPosition() {
    return endPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
  }
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder() {
    return getEndPosition();
  }

  public static final int KIND_FIELD_NUMBER = 4;
  private long kind_;
  /**
   * <code>int64 kind = 4;</code>
   * @return The kind.
   */
  @java.lang.Override
  public long getKind() {
    return kind_;
  }

  public static final int IMPLICIT_FIELD_NUMBER = 5;
  private boolean implicit_;
  /**
   * <code>bool implicit = 5;</code>
   * @return The implicit.
   */
  @java.lang.Override
  public boolean getImplicit() {
    return implicit_;
  }

  public static final int ORDERINGS_FIELD_NUMBER = 10;
  private java.util.List<org.mojo-lang.mojo.db.sql.Ordering> orderings_;
  /**
   * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
   */
  @java.lang.Override
  public java.util.List<org.mojo-lang.mojo.db.sql.Ordering> getOrderingsList() {
    return orderings_;
  }
  /**
   * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.mojo-lang.mojo.db.sql.OrderingOrBuilder> 
      getOrderingsOrBuilderList() {
    return orderings_;
  }
  /**
   * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
   */
  @java.lang.Override
  public int getOrderingsCount() {
    return orderings_.size();
  }
  /**
   * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
   */
  @java.lang.Override
  public org.mojo-lang.mojo.db.sql.Ordering getOrderings(int index) {
    return orderings_.get(index);
  }
  /**
   * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
   */
  @java.lang.Override
  public org.mojo-lang.mojo.db.sql.OrderingOrBuilder getOrderingsOrBuilder(
      int index) {
    return orderings_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startPosition_ != null) {
      output.writeMessage(1, getStartPosition());
    }
    if (endPosition_ != null) {
      output.writeMessage(2, getEndPosition());
    }
    if (kind_ != 0L) {
      output.writeInt64(4, kind_);
    }
    if (implicit_ != false) {
      output.writeBool(5, implicit_);
    }
    for (int i = 0; i < orderings_.size(); i++) {
      output.writeMessage(10, orderings_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startPosition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStartPosition());
    }
    if (endPosition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEndPosition());
    }
    if (kind_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, kind_);
    }
    if (implicit_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, implicit_);
    }
    for (int i = 0; i < orderings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, orderings_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojo-lang.mojo.db.sql.OrderByClause)) {
      return super.equals(obj);
    }
    org.mojo-lang.mojo.db.sql.OrderByClause other = (org.mojo-lang.mojo.db.sql.OrderByClause) obj;

    if (hasStartPosition() != other.hasStartPosition()) return false;
    if (hasStartPosition()) {
      if (!getStartPosition()
          .equals(other.getStartPosition())) return false;
    }
    if (hasEndPosition() != other.hasEndPosition()) return false;
    if (hasEndPosition()) {
      if (!getEndPosition()
          .equals(other.getEndPosition())) return false;
    }
    if (getKind()
        != other.getKind()) return false;
    if (getImplicit()
        != other.getImplicit()) return false;
    if (!getOrderingsList()
        .equals(other.getOrderingsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartPosition()) {
      hash = (37 * hash) + START_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getStartPosition().hashCode();
    }
    if (hasEndPosition()) {
      hash = (37 * hash) + END_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getEndPosition().hashCode();
    }
    hash = (37 * hash) + KIND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getKind());
    hash = (37 * hash) + IMPLICIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getImplicit());
    if (getOrderingsCount() > 0) {
      hash = (37 * hash) + ORDERINGS_FIELD_NUMBER;
      hash = (53 * hash) + getOrderingsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojo-lang.mojo.db.sql.OrderByClause parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojo-lang.mojo.db.sql.OrderByClause parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojo-lang.mojo.db.sql.OrderByClause parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojo-lang.mojo.db.sql.OrderByClause parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojo-lang.mojo.db.sql.OrderByClause parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojo-lang.mojo.db.sql.OrderByClause parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojo-lang.mojo.db.sql.OrderByClause parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojo-lang.mojo.db.sql.OrderByClause parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojo-lang.mojo.db.sql.OrderByClause parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojo-lang.mojo.db.sql.OrderByClause parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojo-lang.mojo.db.sql.OrderByClause parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojo-lang.mojo.db.sql.OrderByClause parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojo-lang.mojo.db.sql.OrderByClause prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.db.sql.OrderByClause}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.db.sql.OrderByClause)
      org.mojo-lang.mojo.db.sql.OrderByClauseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojo-lang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_OrderByClause_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojo-lang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_OrderByClause_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojo-lang.mojo.db.sql.OrderByClause.class, org.mojo-lang.mojo.db.sql.OrderByClause.Builder.class);
    }

    // Construct using org.mojo-lang.mojo.db.sql.OrderByClause.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOrderingsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (startPositionBuilder_ == null) {
        startPosition_ = null;
      } else {
        startPosition_ = null;
        startPositionBuilder_ = null;
      }
      if (endPositionBuilder_ == null) {
        endPosition_ = null;
      } else {
        endPosition_ = null;
        endPositionBuilder_ = null;
      }
      kind_ = 0L;

      implicit_ = false;

      if (orderingsBuilder_ == null) {
        orderings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        orderingsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojo-lang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_OrderByClause_descriptor;
    }

    @java.lang.Override
    public org.mojo-lang.mojo.db.sql.OrderByClause getDefaultInstanceForType() {
      return org.mojo-lang.mojo.db.sql.OrderByClause.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojo-lang.mojo.db.sql.OrderByClause build() {
      org.mojo-lang.mojo.db.sql.OrderByClause result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojo-lang.mojo.db.sql.OrderByClause buildPartial() {
      org.mojo-lang.mojo.db.sql.OrderByClause result = new org.mojo-lang.mojo.db.sql.OrderByClause(this);
      int from_bitField0_ = bitField0_;
      if (startPositionBuilder_ == null) {
        result.startPosition_ = startPosition_;
      } else {
        result.startPosition_ = startPositionBuilder_.build();
      }
      if (endPositionBuilder_ == null) {
        result.endPosition_ = endPosition_;
      } else {
        result.endPosition_ = endPositionBuilder_.build();
      }
      result.kind_ = kind_;
      result.implicit_ = implicit_;
      if (orderingsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          orderings_ = java.util.Collections.unmodifiableList(orderings_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.orderings_ = orderings_;
      } else {
        result.orderings_ = orderingsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojo-lang.mojo.db.sql.OrderByClause) {
        return mergeFrom((org.mojo-lang.mojo.db.sql.OrderByClause)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojo-lang.mojo.db.sql.OrderByClause other) {
      if (other == org.mojo-lang.mojo.db.sql.OrderByClause.getDefaultInstance()) return this;
      if (other.hasStartPosition()) {
        mergeStartPosition(other.getStartPosition());
      }
      if (other.hasEndPosition()) {
        mergeEndPosition(other.getEndPosition());
      }
      if (other.getKind() != 0L) {
        setKind(other.getKind());
      }
      if (other.getImplicit() != false) {
        setImplicit(other.getImplicit());
      }
      if (orderingsBuilder_ == null) {
        if (!other.orderings_.isEmpty()) {
          if (orderings_.isEmpty()) {
            orderings_ = other.orderings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOrderingsIsMutable();
            orderings_.addAll(other.orderings_);
          }
          onChanged();
        }
      } else {
        if (!other.orderings_.isEmpty()) {
          if (orderingsBuilder_.isEmpty()) {
            orderingsBuilder_.dispose();
            orderingsBuilder_ = null;
            orderings_ = other.orderings_;
            bitField0_ = (bitField0_ & ~0x00000001);
            orderingsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrderingsFieldBuilder() : null;
          } else {
            orderingsBuilder_.addAllMessages(other.orderings_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojo-lang.mojo.db.sql.OrderByClause parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojo-lang.mojo.db.sql.OrderByClause) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.mojolang.mojo.lang.Position startPosition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> startPositionBuilder_;
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     * @return Whether the startPosition field is set.
     */
    public boolean hasStartPosition() {
      return startPositionBuilder_ != null || startPosition_ != null;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     * @return The startPosition.
     */
    public org.mojolang.mojo.lang.Position getStartPosition() {
      if (startPositionBuilder_ == null) {
        return startPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
      } else {
        return startPositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder setStartPosition(org.mojolang.mojo.lang.Position value) {
      if (startPositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startPosition_ = value;
        onChanged();
      } else {
        startPositionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder setStartPosition(
        org.mojolang.mojo.lang.Position.Builder builderForValue) {
      if (startPositionBuilder_ == null) {
        startPosition_ = builderForValue.build();
        onChanged();
      } else {
        startPositionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder mergeStartPosition(org.mojolang.mojo.lang.Position value) {
      if (startPositionBuilder_ == null) {
        if (startPosition_ != null) {
          startPosition_ =
            org.mojolang.mojo.lang.Position.newBuilder(startPosition_).mergeFrom(value).buildPartial();
        } else {
          startPosition_ = value;
        }
        onChanged();
      } else {
        startPositionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder clearStartPosition() {
      if (startPositionBuilder_ == null) {
        startPosition_ = null;
        onChanged();
      } else {
        startPosition_ = null;
        startPositionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public org.mojolang.mojo.lang.Position.Builder getStartPositionBuilder() {
      
      onChanged();
      return getStartPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder() {
      if (startPositionBuilder_ != null) {
        return startPositionBuilder_.getMessageOrBuilder();
      } else {
        return startPosition_ == null ?
            org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
      }
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> 
        getStartPositionFieldBuilder() {
      if (startPositionBuilder_ == null) {
        startPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder>(
                getStartPosition(),
                getParentForChildren(),
                isClean());
        startPosition_ = null;
      }
      return startPositionBuilder_;
    }

    private org.mojolang.mojo.lang.Position endPosition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> endPositionBuilder_;
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     * @return Whether the endPosition field is set.
     */
    public boolean hasEndPosition() {
      return endPositionBuilder_ != null || endPosition_ != null;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     * @return The endPosition.
     */
    public org.mojolang.mojo.lang.Position getEndPosition() {
      if (endPositionBuilder_ == null) {
        return endPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
      } else {
        return endPositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder setEndPosition(org.mojolang.mojo.lang.Position value) {
      if (endPositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endPosition_ = value;
        onChanged();
      } else {
        endPositionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder setEndPosition(
        org.mojolang.mojo.lang.Position.Builder builderForValue) {
      if (endPositionBuilder_ == null) {
        endPosition_ = builderForValue.build();
        onChanged();
      } else {
        endPositionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder mergeEndPosition(org.mojolang.mojo.lang.Position value) {
      if (endPositionBuilder_ == null) {
        if (endPosition_ != null) {
          endPosition_ =
            org.mojolang.mojo.lang.Position.newBuilder(endPosition_).mergeFrom(value).buildPartial();
        } else {
          endPosition_ = value;
        }
        onChanged();
      } else {
        endPositionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder clearEndPosition() {
      if (endPositionBuilder_ == null) {
        endPosition_ = null;
        onChanged();
      } else {
        endPosition_ = null;
        endPositionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public org.mojolang.mojo.lang.Position.Builder getEndPositionBuilder() {
      
      onChanged();
      return getEndPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder() {
      if (endPositionBuilder_ != null) {
        return endPositionBuilder_.getMessageOrBuilder();
      } else {
        return endPosition_ == null ?
            org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
      }
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> 
        getEndPositionFieldBuilder() {
      if (endPositionBuilder_ == null) {
        endPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder>(
                getEndPosition(),
                getParentForChildren(),
                isClean());
        endPosition_ = null;
      }
      return endPositionBuilder_;
    }

    private long kind_ ;
    /**
     * <code>int64 kind = 4;</code>
     * @return The kind.
     */
    @java.lang.Override
    public long getKind() {
      return kind_;
    }
    /**
     * <code>int64 kind = 4;</code>
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(long value) {
      
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 kind = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      
      kind_ = 0L;
      onChanged();
      return this;
    }

    private boolean implicit_ ;
    /**
     * <code>bool implicit = 5;</code>
     * @return The implicit.
     */
    @java.lang.Override
    public boolean getImplicit() {
      return implicit_;
    }
    /**
     * <code>bool implicit = 5;</code>
     * @param value The implicit to set.
     * @return This builder for chaining.
     */
    public Builder setImplicit(boolean value) {
      
      implicit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool implicit = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearImplicit() {
      
      implicit_ = false;
      onChanged();
      return this;
    }

    private java.util.List<org.mojo-lang.mojo.db.sql.Ordering> orderings_ =
      java.util.Collections.emptyList();
    private void ensureOrderingsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        orderings_ = new java.util.ArrayList<org.mojo-lang.mojo.db.sql.Ordering>(orderings_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojo-lang.mojo.db.sql.Ordering, org.mojo-lang.mojo.db.sql.Ordering.Builder, org.mojo-lang.mojo.db.sql.OrderingOrBuilder> orderingsBuilder_;

    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public java.util.List<org.mojo-lang.mojo.db.sql.Ordering> getOrderingsList() {
      if (orderingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orderings_);
      } else {
        return orderingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public int getOrderingsCount() {
      if (orderingsBuilder_ == null) {
        return orderings_.size();
      } else {
        return orderingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public org.mojo-lang.mojo.db.sql.Ordering getOrderings(int index) {
      if (orderingsBuilder_ == null) {
        return orderings_.get(index);
      } else {
        return orderingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public Builder setOrderings(
        int index, org.mojo-lang.mojo.db.sql.Ordering value) {
      if (orderingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderingsIsMutable();
        orderings_.set(index, value);
        onChanged();
      } else {
        orderingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public Builder setOrderings(
        int index, org.mojo-lang.mojo.db.sql.Ordering.Builder builderForValue) {
      if (orderingsBuilder_ == null) {
        ensureOrderingsIsMutable();
        orderings_.set(index, builderForValue.build());
        onChanged();
      } else {
        orderingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public Builder addOrderings(org.mojo-lang.mojo.db.sql.Ordering value) {
      if (orderingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderingsIsMutable();
        orderings_.add(value);
        onChanged();
      } else {
        orderingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public Builder addOrderings(
        int index, org.mojo-lang.mojo.db.sql.Ordering value) {
      if (orderingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderingsIsMutable();
        orderings_.add(index, value);
        onChanged();
      } else {
        orderingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public Builder addOrderings(
        org.mojo-lang.mojo.db.sql.Ordering.Builder builderForValue) {
      if (orderingsBuilder_ == null) {
        ensureOrderingsIsMutable();
        orderings_.add(builderForValue.build());
        onChanged();
      } else {
        orderingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public Builder addOrderings(
        int index, org.mojo-lang.mojo.db.sql.Ordering.Builder builderForValue) {
      if (orderingsBuilder_ == null) {
        ensureOrderingsIsMutable();
        orderings_.add(index, builderForValue.build());
        onChanged();
      } else {
        orderingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public Builder addAllOrderings(
        java.lang.Iterable<? extends org.mojo-lang.mojo.db.sql.Ordering> values) {
      if (orderingsBuilder_ == null) {
        ensureOrderingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orderings_);
        onChanged();
      } else {
        orderingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public Builder clearOrderings() {
      if (orderingsBuilder_ == null) {
        orderings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        orderingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public Builder removeOrderings(int index) {
      if (orderingsBuilder_ == null) {
        ensureOrderingsIsMutable();
        orderings_.remove(index);
        onChanged();
      } else {
        orderingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public org.mojo-lang.mojo.db.sql.Ordering.Builder getOrderingsBuilder(
        int index) {
      return getOrderingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public org.mojo-lang.mojo.db.sql.OrderingOrBuilder getOrderingsOrBuilder(
        int index) {
      if (orderingsBuilder_ == null) {
        return orderings_.get(index);  } else {
        return orderingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public java.util.List<? extends org.mojo-lang.mojo.db.sql.OrderingOrBuilder> 
         getOrderingsOrBuilderList() {
      if (orderingsBuilder_ != null) {
        return orderingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orderings_);
      }
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public org.mojo-lang.mojo.db.sql.Ordering.Builder addOrderingsBuilder() {
      return getOrderingsFieldBuilder().addBuilder(
          org.mojo-lang.mojo.db.sql.Ordering.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public org.mojo-lang.mojo.db.sql.Ordering.Builder addOrderingsBuilder(
        int index) {
      return getOrderingsFieldBuilder().addBuilder(
          index, org.mojo-lang.mojo.db.sql.Ordering.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.db.sql.Ordering orderings = 10;</code>
     */
    public java.util.List<org.mojo-lang.mojo.db.sql.Ordering.Builder> 
         getOrderingsBuilderList() {
      return getOrderingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojo-lang.mojo.db.sql.Ordering, org.mojo-lang.mojo.db.sql.Ordering.Builder, org.mojo-lang.mojo.db.sql.OrderingOrBuilder> 
        getOrderingsFieldBuilder() {
      if (orderingsBuilder_ == null) {
        orderingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojo-lang.mojo.db.sql.Ordering, org.mojo-lang.mojo.db.sql.Ordering.Builder, org.mojo-lang.mojo.db.sql.OrderingOrBuilder>(
                orderings_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        orderings_ = null;
      }
      return orderingsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.db.sql.OrderByClause)
  }

  // @@protoc_insertion_point(class_scope:mojo.db.sql.OrderByClause)
  private static final org.mojo-lang.mojo.db.sql.OrderByClause DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojo-lang.mojo.db.sql.OrderByClause();
  }

  public static org.mojo-lang.mojo.db.sql.OrderByClause getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderByClause>
      PARSER = new com.google.protobuf.AbstractParser<OrderByClause>() {
    @java.lang.Override
    public OrderByClause parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderByClause(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderByClause> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderByClause> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojo-lang.mojo.db.sql.OrderByClause getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

