// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/sql/over_clause.proto

package org.mojo-lang.mojo.db.sql;

/**
 * Protobuf type {@code mojo.db.sql.OverClause}
 */
public final class OverClause extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.db.sql.OverClause)
    OverClauseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OverClause.newBuilder() to construct.
  private OverClause(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OverClause() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OverClause();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OverClause(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.mojolang.mojo.lang.Position.Builder subBuilder = null;
            if (startPosition_ != null) {
              subBuilder = startPosition_.toBuilder();
            }
            startPosition_ = input.readMessage(org.mojolang.mojo.lang.Position.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startPosition_);
              startPosition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.mojolang.mojo.lang.Position.Builder subBuilder = null;
            if (endPosition_ != null) {
              subBuilder = endPosition_.toBuilder();
            }
            endPosition_ = input.readMessage(org.mojolang.mojo.lang.Position.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(endPosition_);
              endPosition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            kind_ = input.readInt64();
            break;
          }
          case 40: {

            implicit_ = input.readBool();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 106: {
            org.mojo-lang.mojo.db.sql.PartitionClause.Builder subBuilder = null;
            if (partition_ != null) {
              subBuilder = partition_.toBuilder();
            }
            partition_ = input.readMessage(org.mojo-lang.mojo.db.sql.PartitionClause.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(partition_);
              partition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 114: {
            org.mojo-lang.mojo.db.sql.OrderByClause.Builder subBuilder = null;
            if (orderBy_ != null) {
              subBuilder = orderBy_.toBuilder();
            }
            orderBy_ = input.readMessage(org.mojo-lang.mojo.db.sql.OrderByClause.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(orderBy_);
              orderBy_ = subBuilder.buildPartial();
            }

            break;
          }
          case 122: {
            org.mojo-lang.mojo.db.sql.Window.Frame.Builder subBuilder = null;
            if (frame_ != null) {
              subBuilder = frame_.toBuilder();
            }
            frame_ = input.readMessage(org.mojo-lang.mojo.db.sql.Window.Frame.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(frame_);
              frame_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojo-lang.mojo.db.sql.OverClauseProto.internal_static_mojo_db_sql_OverClause_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojo-lang.mojo.db.sql.OverClauseProto.internal_static_mojo_db_sql_OverClause_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojo-lang.mojo.db.sql.OverClause.class, org.mojo-lang.mojo.db.sql.OverClause.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 10;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 10;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 10;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTITION_FIELD_NUMBER = 13;
  private org.mojo-lang.mojo.db.sql.PartitionClause partition_;
  /**
   * <code>.mojo.db.sql.PartitionClause partition = 13;</code>
   * @return Whether the partition field is set.
   */
  @java.lang.Override
  public boolean hasPartition() {
    return partition_ != null;
  }
  /**
   * <code>.mojo.db.sql.PartitionClause partition = 13;</code>
   * @return The partition.
   */
  @java.lang.Override
  public org.mojo-lang.mojo.db.sql.PartitionClause getPartition() {
    return partition_ == null ? org.mojo-lang.mojo.db.sql.PartitionClause.getDefaultInstance() : partition_;
  }
  /**
   * <code>.mojo.db.sql.PartitionClause partition = 13;</code>
   */
  @java.lang.Override
  public org.mojo-lang.mojo.db.sql.PartitionClauseOrBuilder getPartitionOrBuilder() {
    return getPartition();
  }

  public static final int ORDER_BY_FIELD_NUMBER = 14;
  private org.mojo-lang.mojo.db.sql.OrderByClause orderBy_;
  /**
   * <code>.mojo.db.sql.OrderByClause order_by = 14;</code>
   * @return Whether the orderBy field is set.
   */
  @java.lang.Override
  public boolean hasOrderBy() {
    return orderBy_ != null;
  }
  /**
   * <code>.mojo.db.sql.OrderByClause order_by = 14;</code>
   * @return The orderBy.
   */
  @java.lang.Override
  public org.mojo-lang.mojo.db.sql.OrderByClause getOrderBy() {
    return orderBy_ == null ? org.mojo-lang.mojo.db.sql.OrderByClause.getDefaultInstance() : orderBy_;
  }
  /**
   * <code>.mojo.db.sql.OrderByClause order_by = 14;</code>
   */
  @java.lang.Override
  public org.mojo-lang.mojo.db.sql.OrderByClauseOrBuilder getOrderByOrBuilder() {
    return getOrderBy();
  }

  public static final int FRAME_FIELD_NUMBER = 15;
  private org.mojo-lang.mojo.db.sql.Window.Frame frame_;
  /**
   * <code>.mojo.db.sql.Window.Frame frame = 15;</code>
   * @return Whether the frame field is set.
   */
  @java.lang.Override
  public boolean hasFrame() {
    return frame_ != null;
  }
  /**
   * <code>.mojo.db.sql.Window.Frame frame = 15;</code>
   * @return The frame.
   */
  @java.lang.Override
  public org.mojo-lang.mojo.db.sql.Window.Frame getFrame() {
    return frame_ == null ? org.mojo-lang.mojo.db.sql.Window.Frame.getDefaultInstance() : frame_;
  }
  /**
   * <code>.mojo.db.sql.Window.Frame frame = 15;</code>
   */
  @java.lang.Override
  public org.mojo-lang.mojo.db.sql.Window.FrameOrBuilder getFrameOrBuilder() {
    return getFrame();
  }

  public static final int START_POSITION_FIELD_NUMBER = 1;
  private org.mojolang.mojo.lang.Position startPosition_;
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return Whether the startPosition field is set.
   */
  @java.lang.Override
  public boolean hasStartPosition() {
    return startPosition_ != null;
  }
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return The startPosition.
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Position getStartPosition() {
    return startPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
  }
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder() {
    return getStartPosition();
  }

  public static final int END_POSITION_FIELD_NUMBER = 2;
  private org.mojolang.mojo.lang.Position endPosition_;
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return Whether the endPosition field is set.
   */
  @java.lang.Override
  public boolean hasEndPosition() {
    return endPosition_ != null;
  }
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return The endPosition.
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Position getEndPosition() {
    return endPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
  }
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder() {
    return getEndPosition();
  }

  public static final int KIND_FIELD_NUMBER = 4;
  private long kind_;
  /**
   * <code>int64 kind = 4;</code>
   * @return The kind.
   */
  @java.lang.Override
  public long getKind() {
    return kind_;
  }

  public static final int IMPLICIT_FIELD_NUMBER = 5;
  private boolean implicit_;
  /**
   * <code>bool implicit = 5;</code>
   * @return The implicit.
   */
  @java.lang.Override
  public boolean getImplicit() {
    return implicit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startPosition_ != null) {
      output.writeMessage(1, getStartPosition());
    }
    if (endPosition_ != null) {
      output.writeMessage(2, getEndPosition());
    }
    if (kind_ != 0L) {
      output.writeInt64(4, kind_);
    }
    if (implicit_ != false) {
      output.writeBool(5, implicit_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, name_);
    }
    if (partition_ != null) {
      output.writeMessage(13, getPartition());
    }
    if (orderBy_ != null) {
      output.writeMessage(14, getOrderBy());
    }
    if (frame_ != null) {
      output.writeMessage(15, getFrame());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startPosition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStartPosition());
    }
    if (endPosition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEndPosition());
    }
    if (kind_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, kind_);
    }
    if (implicit_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, implicit_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, name_);
    }
    if (partition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getPartition());
    }
    if (orderBy_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, getOrderBy());
    }
    if (frame_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getFrame());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojo-lang.mojo.db.sql.OverClause)) {
      return super.equals(obj);
    }
    org.mojo-lang.mojo.db.sql.OverClause other = (org.mojo-lang.mojo.db.sql.OverClause) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (hasPartition() != other.hasPartition()) return false;
    if (hasPartition()) {
      if (!getPartition()
          .equals(other.getPartition())) return false;
    }
    if (hasOrderBy() != other.hasOrderBy()) return false;
    if (hasOrderBy()) {
      if (!getOrderBy()
          .equals(other.getOrderBy())) return false;
    }
    if (hasFrame() != other.hasFrame()) return false;
    if (hasFrame()) {
      if (!getFrame()
          .equals(other.getFrame())) return false;
    }
    if (hasStartPosition() != other.hasStartPosition()) return false;
    if (hasStartPosition()) {
      if (!getStartPosition()
          .equals(other.getStartPosition())) return false;
    }
    if (hasEndPosition() != other.hasEndPosition()) return false;
    if (hasEndPosition()) {
      if (!getEndPosition()
          .equals(other.getEndPosition())) return false;
    }
    if (getKind()
        != other.getKind()) return false;
    if (getImplicit()
        != other.getImplicit()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasPartition()) {
      hash = (37 * hash) + PARTITION_FIELD_NUMBER;
      hash = (53 * hash) + getPartition().hashCode();
    }
    if (hasOrderBy()) {
      hash = (37 * hash) + ORDER_BY_FIELD_NUMBER;
      hash = (53 * hash) + getOrderBy().hashCode();
    }
    if (hasFrame()) {
      hash = (37 * hash) + FRAME_FIELD_NUMBER;
      hash = (53 * hash) + getFrame().hashCode();
    }
    if (hasStartPosition()) {
      hash = (37 * hash) + START_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getStartPosition().hashCode();
    }
    if (hasEndPosition()) {
      hash = (37 * hash) + END_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getEndPosition().hashCode();
    }
    hash = (37 * hash) + KIND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getKind());
    hash = (37 * hash) + IMPLICIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getImplicit());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojo-lang.mojo.db.sql.OverClause parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojo-lang.mojo.db.sql.OverClause parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojo-lang.mojo.db.sql.OverClause parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojo-lang.mojo.db.sql.OverClause parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojo-lang.mojo.db.sql.OverClause parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojo-lang.mojo.db.sql.OverClause parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojo-lang.mojo.db.sql.OverClause parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojo-lang.mojo.db.sql.OverClause parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojo-lang.mojo.db.sql.OverClause parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojo-lang.mojo.db.sql.OverClause parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojo-lang.mojo.db.sql.OverClause parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojo-lang.mojo.db.sql.OverClause parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojo-lang.mojo.db.sql.OverClause prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.db.sql.OverClause}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.db.sql.OverClause)
      org.mojo-lang.mojo.db.sql.OverClauseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojo-lang.mojo.db.sql.OverClauseProto.internal_static_mojo_db_sql_OverClause_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojo-lang.mojo.db.sql.OverClauseProto.internal_static_mojo_db_sql_OverClause_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojo-lang.mojo.db.sql.OverClause.class, org.mojo-lang.mojo.db.sql.OverClause.Builder.class);
    }

    // Construct using org.mojo-lang.mojo.db.sql.OverClause.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      if (partitionBuilder_ == null) {
        partition_ = null;
      } else {
        partition_ = null;
        partitionBuilder_ = null;
      }
      if (orderByBuilder_ == null) {
        orderBy_ = null;
      } else {
        orderBy_ = null;
        orderByBuilder_ = null;
      }
      if (frameBuilder_ == null) {
        frame_ = null;
      } else {
        frame_ = null;
        frameBuilder_ = null;
      }
      if (startPositionBuilder_ == null) {
        startPosition_ = null;
      } else {
        startPosition_ = null;
        startPositionBuilder_ = null;
      }
      if (endPositionBuilder_ == null) {
        endPosition_ = null;
      } else {
        endPosition_ = null;
        endPositionBuilder_ = null;
      }
      kind_ = 0L;

      implicit_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojo-lang.mojo.db.sql.OverClauseProto.internal_static_mojo_db_sql_OverClause_descriptor;
    }

    @java.lang.Override
    public org.mojo-lang.mojo.db.sql.OverClause getDefaultInstanceForType() {
      return org.mojo-lang.mojo.db.sql.OverClause.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojo-lang.mojo.db.sql.OverClause build() {
      org.mojo-lang.mojo.db.sql.OverClause result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojo-lang.mojo.db.sql.OverClause buildPartial() {
      org.mojo-lang.mojo.db.sql.OverClause result = new org.mojo-lang.mojo.db.sql.OverClause(this);
      result.name_ = name_;
      if (partitionBuilder_ == null) {
        result.partition_ = partition_;
      } else {
        result.partition_ = partitionBuilder_.build();
      }
      if (orderByBuilder_ == null) {
        result.orderBy_ = orderBy_;
      } else {
        result.orderBy_ = orderByBuilder_.build();
      }
      if (frameBuilder_ == null) {
        result.frame_ = frame_;
      } else {
        result.frame_ = frameBuilder_.build();
      }
      if (startPositionBuilder_ == null) {
        result.startPosition_ = startPosition_;
      } else {
        result.startPosition_ = startPositionBuilder_.build();
      }
      if (endPositionBuilder_ == null) {
        result.endPosition_ = endPosition_;
      } else {
        result.endPosition_ = endPositionBuilder_.build();
      }
      result.kind_ = kind_;
      result.implicit_ = implicit_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojo-lang.mojo.db.sql.OverClause) {
        return mergeFrom((org.mojo-lang.mojo.db.sql.OverClause)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojo-lang.mojo.db.sql.OverClause other) {
      if (other == org.mojo-lang.mojo.db.sql.OverClause.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasPartition()) {
        mergePartition(other.getPartition());
      }
      if (other.hasOrderBy()) {
        mergeOrderBy(other.getOrderBy());
      }
      if (other.hasFrame()) {
        mergeFrame(other.getFrame());
      }
      if (other.hasStartPosition()) {
        mergeStartPosition(other.getStartPosition());
      }
      if (other.hasEndPosition()) {
        mergeEndPosition(other.getEndPosition());
      }
      if (other.getKind() != 0L) {
        setKind(other.getKind());
      }
      if (other.getImplicit() != false) {
        setImplicit(other.getImplicit());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojo-lang.mojo.db.sql.OverClause parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojo-lang.mojo.db.sql.OverClause) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 10;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 10;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 10;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 10;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private org.mojo-lang.mojo.db.sql.PartitionClause partition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojo-lang.mojo.db.sql.PartitionClause, org.mojo-lang.mojo.db.sql.PartitionClause.Builder, org.mojo-lang.mojo.db.sql.PartitionClauseOrBuilder> partitionBuilder_;
    /**
     * <code>.mojo.db.sql.PartitionClause partition = 13;</code>
     * @return Whether the partition field is set.
     */
    public boolean hasPartition() {
      return partitionBuilder_ != null || partition_ != null;
    }
    /**
     * <code>.mojo.db.sql.PartitionClause partition = 13;</code>
     * @return The partition.
     */
    public org.mojo-lang.mojo.db.sql.PartitionClause getPartition() {
      if (partitionBuilder_ == null) {
        return partition_ == null ? org.mojo-lang.mojo.db.sql.PartitionClause.getDefaultInstance() : partition_;
      } else {
        return partitionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.db.sql.PartitionClause partition = 13;</code>
     */
    public Builder setPartition(org.mojo-lang.mojo.db.sql.PartitionClause value) {
      if (partitionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        partition_ = value;
        onChanged();
      } else {
        partitionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.PartitionClause partition = 13;</code>
     */
    public Builder setPartition(
        org.mojo-lang.mojo.db.sql.PartitionClause.Builder builderForValue) {
      if (partitionBuilder_ == null) {
        partition_ = builderForValue.build();
        onChanged();
      } else {
        partitionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.PartitionClause partition = 13;</code>
     */
    public Builder mergePartition(org.mojo-lang.mojo.db.sql.PartitionClause value) {
      if (partitionBuilder_ == null) {
        if (partition_ != null) {
          partition_ =
            org.mojo-lang.mojo.db.sql.PartitionClause.newBuilder(partition_).mergeFrom(value).buildPartial();
        } else {
          partition_ = value;
        }
        onChanged();
      } else {
        partitionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.PartitionClause partition = 13;</code>
     */
    public Builder clearPartition() {
      if (partitionBuilder_ == null) {
        partition_ = null;
        onChanged();
      } else {
        partition_ = null;
        partitionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.PartitionClause partition = 13;</code>
     */
    public org.mojo-lang.mojo.db.sql.PartitionClause.Builder getPartitionBuilder() {
      
      onChanged();
      return getPartitionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.db.sql.PartitionClause partition = 13;</code>
     */
    public org.mojo-lang.mojo.db.sql.PartitionClauseOrBuilder getPartitionOrBuilder() {
      if (partitionBuilder_ != null) {
        return partitionBuilder_.getMessageOrBuilder();
      } else {
        return partition_ == null ?
            org.mojo-lang.mojo.db.sql.PartitionClause.getDefaultInstance() : partition_;
      }
    }
    /**
     * <code>.mojo.db.sql.PartitionClause partition = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojo-lang.mojo.db.sql.PartitionClause, org.mojo-lang.mojo.db.sql.PartitionClause.Builder, org.mojo-lang.mojo.db.sql.PartitionClauseOrBuilder> 
        getPartitionFieldBuilder() {
      if (partitionBuilder_ == null) {
        partitionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojo-lang.mojo.db.sql.PartitionClause, org.mojo-lang.mojo.db.sql.PartitionClause.Builder, org.mojo-lang.mojo.db.sql.PartitionClauseOrBuilder>(
                getPartition(),
                getParentForChildren(),
                isClean());
        partition_ = null;
      }
      return partitionBuilder_;
    }

    private org.mojo-lang.mojo.db.sql.OrderByClause orderBy_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojo-lang.mojo.db.sql.OrderByClause, org.mojo-lang.mojo.db.sql.OrderByClause.Builder, org.mojo-lang.mojo.db.sql.OrderByClauseOrBuilder> orderByBuilder_;
    /**
     * <code>.mojo.db.sql.OrderByClause order_by = 14;</code>
     * @return Whether the orderBy field is set.
     */
    public boolean hasOrderBy() {
      return orderByBuilder_ != null || orderBy_ != null;
    }
    /**
     * <code>.mojo.db.sql.OrderByClause order_by = 14;</code>
     * @return The orderBy.
     */
    public org.mojo-lang.mojo.db.sql.OrderByClause getOrderBy() {
      if (orderByBuilder_ == null) {
        return orderBy_ == null ? org.mojo-lang.mojo.db.sql.OrderByClause.getDefaultInstance() : orderBy_;
      } else {
        return orderByBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.db.sql.OrderByClause order_by = 14;</code>
     */
    public Builder setOrderBy(org.mojo-lang.mojo.db.sql.OrderByClause value) {
      if (orderByBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        orderBy_ = value;
        onChanged();
      } else {
        orderByBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.OrderByClause order_by = 14;</code>
     */
    public Builder setOrderBy(
        org.mojo-lang.mojo.db.sql.OrderByClause.Builder builderForValue) {
      if (orderByBuilder_ == null) {
        orderBy_ = builderForValue.build();
        onChanged();
      } else {
        orderByBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.OrderByClause order_by = 14;</code>
     */
    public Builder mergeOrderBy(org.mojo-lang.mojo.db.sql.OrderByClause value) {
      if (orderByBuilder_ == null) {
        if (orderBy_ != null) {
          orderBy_ =
            org.mojo-lang.mojo.db.sql.OrderByClause.newBuilder(orderBy_).mergeFrom(value).buildPartial();
        } else {
          orderBy_ = value;
        }
        onChanged();
      } else {
        orderByBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.OrderByClause order_by = 14;</code>
     */
    public Builder clearOrderBy() {
      if (orderByBuilder_ == null) {
        orderBy_ = null;
        onChanged();
      } else {
        orderBy_ = null;
        orderByBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.OrderByClause order_by = 14;</code>
     */
    public org.mojo-lang.mojo.db.sql.OrderByClause.Builder getOrderByBuilder() {
      
      onChanged();
      return getOrderByFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.db.sql.OrderByClause order_by = 14;</code>
     */
    public org.mojo-lang.mojo.db.sql.OrderByClauseOrBuilder getOrderByOrBuilder() {
      if (orderByBuilder_ != null) {
        return orderByBuilder_.getMessageOrBuilder();
      } else {
        return orderBy_ == null ?
            org.mojo-lang.mojo.db.sql.OrderByClause.getDefaultInstance() : orderBy_;
      }
    }
    /**
     * <code>.mojo.db.sql.OrderByClause order_by = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojo-lang.mojo.db.sql.OrderByClause, org.mojo-lang.mojo.db.sql.OrderByClause.Builder, org.mojo-lang.mojo.db.sql.OrderByClauseOrBuilder> 
        getOrderByFieldBuilder() {
      if (orderByBuilder_ == null) {
        orderByBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojo-lang.mojo.db.sql.OrderByClause, org.mojo-lang.mojo.db.sql.OrderByClause.Builder, org.mojo-lang.mojo.db.sql.OrderByClauseOrBuilder>(
                getOrderBy(),
                getParentForChildren(),
                isClean());
        orderBy_ = null;
      }
      return orderByBuilder_;
    }

    private org.mojo-lang.mojo.db.sql.Window.Frame frame_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojo-lang.mojo.db.sql.Window.Frame, org.mojo-lang.mojo.db.sql.Window.Frame.Builder, org.mojo-lang.mojo.db.sql.Window.FrameOrBuilder> frameBuilder_;
    /**
     * <code>.mojo.db.sql.Window.Frame frame = 15;</code>
     * @return Whether the frame field is set.
     */
    public boolean hasFrame() {
      return frameBuilder_ != null || frame_ != null;
    }
    /**
     * <code>.mojo.db.sql.Window.Frame frame = 15;</code>
     * @return The frame.
     */
    public org.mojo-lang.mojo.db.sql.Window.Frame getFrame() {
      if (frameBuilder_ == null) {
        return frame_ == null ? org.mojo-lang.mojo.db.sql.Window.Frame.getDefaultInstance() : frame_;
      } else {
        return frameBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.db.sql.Window.Frame frame = 15;</code>
     */
    public Builder setFrame(org.mojo-lang.mojo.db.sql.Window.Frame value) {
      if (frameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        frame_ = value;
        onChanged();
      } else {
        frameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.Window.Frame frame = 15;</code>
     */
    public Builder setFrame(
        org.mojo-lang.mojo.db.sql.Window.Frame.Builder builderForValue) {
      if (frameBuilder_ == null) {
        frame_ = builderForValue.build();
        onChanged();
      } else {
        frameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.Window.Frame frame = 15;</code>
     */
    public Builder mergeFrame(org.mojo-lang.mojo.db.sql.Window.Frame value) {
      if (frameBuilder_ == null) {
        if (frame_ != null) {
          frame_ =
            org.mojo-lang.mojo.db.sql.Window.Frame.newBuilder(frame_).mergeFrom(value).buildPartial();
        } else {
          frame_ = value;
        }
        onChanged();
      } else {
        frameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.Window.Frame frame = 15;</code>
     */
    public Builder clearFrame() {
      if (frameBuilder_ == null) {
        frame_ = null;
        onChanged();
      } else {
        frame_ = null;
        frameBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.db.sql.Window.Frame frame = 15;</code>
     */
    public org.mojo-lang.mojo.db.sql.Window.Frame.Builder getFrameBuilder() {
      
      onChanged();
      return getFrameFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.db.sql.Window.Frame frame = 15;</code>
     */
    public org.mojo-lang.mojo.db.sql.Window.FrameOrBuilder getFrameOrBuilder() {
      if (frameBuilder_ != null) {
        return frameBuilder_.getMessageOrBuilder();
      } else {
        return frame_ == null ?
            org.mojo-lang.mojo.db.sql.Window.Frame.getDefaultInstance() : frame_;
      }
    }
    /**
     * <code>.mojo.db.sql.Window.Frame frame = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojo-lang.mojo.db.sql.Window.Frame, org.mojo-lang.mojo.db.sql.Window.Frame.Builder, org.mojo-lang.mojo.db.sql.Window.FrameOrBuilder> 
        getFrameFieldBuilder() {
      if (frameBuilder_ == null) {
        frameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojo-lang.mojo.db.sql.Window.Frame, org.mojo-lang.mojo.db.sql.Window.Frame.Builder, org.mojo-lang.mojo.db.sql.Window.FrameOrBuilder>(
                getFrame(),
                getParentForChildren(),
                isClean());
        frame_ = null;
      }
      return frameBuilder_;
    }

    private org.mojolang.mojo.lang.Position startPosition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> startPositionBuilder_;
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     * @return Whether the startPosition field is set.
     */
    public boolean hasStartPosition() {
      return startPositionBuilder_ != null || startPosition_ != null;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     * @return The startPosition.
     */
    public org.mojolang.mojo.lang.Position getStartPosition() {
      if (startPositionBuilder_ == null) {
        return startPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
      } else {
        return startPositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder setStartPosition(org.mojolang.mojo.lang.Position value) {
      if (startPositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startPosition_ = value;
        onChanged();
      } else {
        startPositionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder setStartPosition(
        org.mojolang.mojo.lang.Position.Builder builderForValue) {
      if (startPositionBuilder_ == null) {
        startPosition_ = builderForValue.build();
        onChanged();
      } else {
        startPositionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder mergeStartPosition(org.mojolang.mojo.lang.Position value) {
      if (startPositionBuilder_ == null) {
        if (startPosition_ != null) {
          startPosition_ =
            org.mojolang.mojo.lang.Position.newBuilder(startPosition_).mergeFrom(value).buildPartial();
        } else {
          startPosition_ = value;
        }
        onChanged();
      } else {
        startPositionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder clearStartPosition() {
      if (startPositionBuilder_ == null) {
        startPosition_ = null;
        onChanged();
      } else {
        startPosition_ = null;
        startPositionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public org.mojolang.mojo.lang.Position.Builder getStartPositionBuilder() {
      
      onChanged();
      return getStartPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder() {
      if (startPositionBuilder_ != null) {
        return startPositionBuilder_.getMessageOrBuilder();
      } else {
        return startPosition_ == null ?
            org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
      }
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> 
        getStartPositionFieldBuilder() {
      if (startPositionBuilder_ == null) {
        startPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder>(
                getStartPosition(),
                getParentForChildren(),
                isClean());
        startPosition_ = null;
      }
      return startPositionBuilder_;
    }

    private org.mojolang.mojo.lang.Position endPosition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> endPositionBuilder_;
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     * @return Whether the endPosition field is set.
     */
    public boolean hasEndPosition() {
      return endPositionBuilder_ != null || endPosition_ != null;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     * @return The endPosition.
     */
    public org.mojolang.mojo.lang.Position getEndPosition() {
      if (endPositionBuilder_ == null) {
        return endPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
      } else {
        return endPositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder setEndPosition(org.mojolang.mojo.lang.Position value) {
      if (endPositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endPosition_ = value;
        onChanged();
      } else {
        endPositionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder setEndPosition(
        org.mojolang.mojo.lang.Position.Builder builderForValue) {
      if (endPositionBuilder_ == null) {
        endPosition_ = builderForValue.build();
        onChanged();
      } else {
        endPositionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder mergeEndPosition(org.mojolang.mojo.lang.Position value) {
      if (endPositionBuilder_ == null) {
        if (endPosition_ != null) {
          endPosition_ =
            org.mojolang.mojo.lang.Position.newBuilder(endPosition_).mergeFrom(value).buildPartial();
        } else {
          endPosition_ = value;
        }
        onChanged();
      } else {
        endPositionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder clearEndPosition() {
      if (endPositionBuilder_ == null) {
        endPosition_ = null;
        onChanged();
      } else {
        endPosition_ = null;
        endPositionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public org.mojolang.mojo.lang.Position.Builder getEndPositionBuilder() {
      
      onChanged();
      return getEndPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder() {
      if (endPositionBuilder_ != null) {
        return endPositionBuilder_.getMessageOrBuilder();
      } else {
        return endPosition_ == null ?
            org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
      }
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> 
        getEndPositionFieldBuilder() {
      if (endPositionBuilder_ == null) {
        endPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder>(
                getEndPosition(),
                getParentForChildren(),
                isClean());
        endPosition_ = null;
      }
      return endPositionBuilder_;
    }

    private long kind_ ;
    /**
     * <code>int64 kind = 4;</code>
     * @return The kind.
     */
    @java.lang.Override
    public long getKind() {
      return kind_;
    }
    /**
     * <code>int64 kind = 4;</code>
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(long value) {
      
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 kind = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      
      kind_ = 0L;
      onChanged();
      return this;
    }

    private boolean implicit_ ;
    /**
     * <code>bool implicit = 5;</code>
     * @return The implicit.
     */
    @java.lang.Override
    public boolean getImplicit() {
      return implicit_;
    }
    /**
     * <code>bool implicit = 5;</code>
     * @param value The implicit to set.
     * @return This builder for chaining.
     */
    public Builder setImplicit(boolean value) {
      
      implicit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool implicit = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearImplicit() {
      
      implicit_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.db.sql.OverClause)
  }

  // @@protoc_insertion_point(class_scope:mojo.db.sql.OverClause)
  private static final org.mojo-lang.mojo.db.sql.OverClause DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojo-lang.mojo.db.sql.OverClause();
  }

  public static org.mojo-lang.mojo.db.sql.OverClause getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OverClause>
      PARSER = new com.google.protobuf.AbstractParser<OverClause>() {
    @java.lang.Override
    public OverClause parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OverClause(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OverClause> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OverClause> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojo-lang.mojo.db.sql.OverClause getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

