// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/sql/source_file.proto

package org.mojo-lang.mojo.db.sql;

public final class SourceFileProto {
  private SourceFileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_SourceFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_SourceFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035mojo/db/sql/source_file.proto\022\013mojo.db" +
      ".sql\032\033mojo/db/sql/statement.proto\"8\n\nSou" +
      "rceFile\022*\n\nstatements\030\n \003(\0132\026.mojo.db.sq" +
      "l.StatementB^\n\031org.mojo-lang.mojo.db.sql" +
      "B\017SourceFileProtoP\001Z.github.com/mojo-lan" +
      "g/db/go/pkg/mojo/db/sql;sqlb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojo-lang.mojo.db.sql.StatementProto.getDescriptor(),
        });
    internal_static_mojo_db_sql_SourceFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_db_sql_SourceFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_SourceFile_descriptor,
        new java.lang.String[] { "Statements", });
    org.mojo-lang.mojo.db.sql.StatementProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
