// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/sql/sql.proto

package org.mojo-lang.mojo.db.sql;

public final class SqlProto {
  private SqlProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_BinaryExpr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_BinaryExpr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_Column_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_Column_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_AllColumn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_AllColumn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_DerivedColumn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_DerivedColumn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_CompoundSelect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_CompoundSelect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_Expression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_Expression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_FromClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_FromClause_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_GroupByClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_GroupByClause_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_HavingClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_HavingClause_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_JoinClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_JoinClause_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_JoinClause_Constraint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_JoinClause_Constraint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_LimitClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_LimitClause_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_OffsetClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_OffsetClause_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_OrderByClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_OrderByClause_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_Ordering_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_Ordering_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_PostfixUnaryExpr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_PostfixUnaryExpr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_PrefixUnaryExpr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_PrefixUnaryExpr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_SelectClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_SelectClause_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_SelectStmt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_SelectStmt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_SubqueryExpr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_SubqueryExpr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_Table_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_Table_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_TableName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_TableName_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_TableFunctionName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_TableFunctionName_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_TableQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_TableQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_UnaryExpr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_UnaryExpr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_ValuesClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_ValuesClause_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_WhereClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_WhereClause_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_TemporaryTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_TemporaryTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_WithClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_WithClause_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025mojo/db/sql/sql.proto\022\013mojo.db.sql\032\036mo" +
      "jo/db/sql/between_expr.proto\032%mojo/db/sq" +
      "l/bind_parameter_expr.proto\032#mojo/db/sql" +
      "/blob_literal_expr.proto\032\033mojo/db/sql/ca" +
      "se_expr.proto\032\030mojo/db/sql/clause.proto\032" +
      "!mojo/db/sql/column_ref_expr.proto\032(mojo" +
      "/db/sql/data_manipulation_stmt.proto\032%mo" +
      "jo/db/sql/data_set_quantifier.proto\032$moj" +
      "o/db/sql/function_call_expr.proto\032!mojo/" +
      "db/sql/identifier_expr.proto\032\031mojo/db/sq" +
      "l/in_expr.proto\032\027mojo/db/sql/order.proto" +
      "\032\024mojo/lang/lang.proto\"\304\006\n\nBinaryExpr\022+\n" +
      "\016start_position\030\001 \001(\0132\023.mojo.lang.Positi" +
      "on\022)\n\014end_position\030\002 \001(\0132\023.mojo.lang.Pos" +
      "ition\022\014\n\004kind\030\004 \001(\005\022\020\n\010implicit\030\005 \001(\010\0222\n" +
      "\010operator\030\n \001(\0162 .mojo.db.sql.BinaryExpr" +
      ".Operator\022\027\n\017operator_symbol\030\013 \001(\t\022\033\n\023op" +
      "erator_precedence\030\014 \001(\005\022.\n\rleft_argument" +
      "\030\017 \001(\0132\027.mojo.db.sql.Expression\022/\n\016right" +
      "_argument\030\020 \001(\0132\027.mojo.db.sql.Expression" +
      "\"\362\003\n\010Operator\022\030\n\024OPERATOR_UNSPECIFIED\020\000\022" +
      "\021\n\rOPERATOR_PLUS\020\001\022\022\n\016OPERATOR_MINUS\020\002\022\020" +
      "\n\014OPERATOR_MUL\020\003\022\020\n\014OPERATOR_DIV\020\004\022\020\n\014OP" +
      "ERATOR_MOD\020\005\022\017\n\013OPERATOR_LT\020\n\022\017\n\013OPERATO" +
      "R_GT\020\013\022\020\n\014OPERATOR_LTE\020\014\022\020\n\014OPERATOR_GTE" +
      "\020\r\022\022\n\016OPERATOR_EQUAL\020\016\022\026\n\022OPERATOR_NOT_E" +
      "QUAL\020\017\022\023\n\017OPERATOR_ASSIGN\020\022\022\020\n\014OPERATOR_" +
      "AND\020\024\022\017\n\013OPERATOR_OR\020\025\022\024\n\020OPERATOR_BIT_A" +
      "ND\020\031\022\023\n\017OPERATOR_BIT_OR\020\032\022\024\n\020OPERATOR_BI" +
      "T_XOR\020\033\022\017\n\013OPERATOR_IS\020\036\022\023\n\017OPERATOR_IS_" +
      "NOT\020\037\022\017\n\013OPERATOR_IN\020(\022\021\n\rOPERATOR_LIKE\020" +
      ")\022\022\n\016OPERATOR_MATCH\020*\022\023\n\017OPERATOR_REGEXP" +
      "\020+\022\021\n\rOPERATOR_GLOB\0202\"~\n\006Column\0220\n\016all_c" +
      "olumn_val\030\001 \001(\0132\026.mojo.db.sql.AllColumnH" +
      "\000\0228\n\022derived_column_val\030\002 \001(\0132\032.mojo.db." +
      "sql.DerivedColumnH\000B\010\n\006column\"\037\n\tAllColu" +
      "mn\022\022\n\ntable_name\030\001 \001(\t\"B\n\rDerivedColumn\022" +
      "%\n\004expr\030\001 \001(\0132\027.mojo.db.sql.Expression\022\n" +
      "\n\002as\030\002 \001(\t\"\306\006\n\016CompoundSelect\022+\n\016start_p" +
      "osition\030\001 \001(\0132\023.mojo.lang.Position\022)\n\014en" +
      "d_position\030\002 \001(\0132\023.mojo.lang.Position\022\014\n" +
      "\004kind\030\004 \001(\003\022\020\n\010implicit\030\005 \001(\010\022%\n\004with\030\n " +
      "\001(\0132\027.mojo.db.sql.WithClause\0222\n\rselect_c" +
      "lause\030\013 \001(\0132\031.mojo.db.sql.SelectClauseH\000" +
      "\0226\n\017compound_select\030\014 \001(\0132\033.mojo.db.sql." +
      "CompoundSelectH\000\022)\n\006values\030\r \001(\0132\031.mojo." +
      "db.sql.ValuesClause\022%\n\004from\030\016 \001(\0132\027.mojo" +
      ".db.sql.FromClause\022\'\n\005where\030\017 \001(\0132\030.mojo" +
      ".db.sql.WhereClause\022,\n\010group_by\030\020 \001(\0132\032." +
      "mojo.db.sql.GroupByClause\022)\n\006having\030\021 \001(" +
      "\0132\031.mojo.db.sql.HavingClause\022,\n\010order_by" +
      "\030\024 \001(\0132\032.mojo.db.sql.OrderByClause\022\'\n\005li" +
      "mit\030\025 \001(\0132\030.mojo.db.sql.LimitClause\0226\n\010o" +
      "perator\030\036 \001(\0162$.mojo.db.sql.CompoundSele" +
      "ct.Operator\022)\n\004left\030\037 \001(\0132\033.mojo.db.sql." +
      "CompoundSelect\022*\n\005right\030  \001(\0132\033.mojo.db." +
      "sql.CompoundSelect\"e\n\010Operator\022\030\n\024OPERAT" +
      "OR_UNSPECIFIED\020\000\022\022\n\016OPERATOR_UNION\020\001\022\026\n\022" +
      "OPERATOR_INTERSECT\020\002\022\023\n\017OPERATOR_EXCEPT\020" +
      "\003B\010\n\006select\"\313\007\n\nExpression\0227\n\021null_liter" +
      "al_expr\030\001 \001(\0132\032.mojo.lang.NullLiteralExp" +
      "rH\000\0227\n\021bool_literal_expr\030\002 \001(\0132\032.mojo.la" +
      "ng.BoolLiteralExprH\000\022=\n\024integer_literal_" +
      "expr\030\003 \001(\0132\035.mojo.lang.IntegerLiteralExp" +
      "rH\000\0229\n\022float_literal_expr\030\004 \001(\0132\033.mojo.l" +
      "ang.FloatLiteralExprH\000\022;\n\023string_literal" +
      "_expr\030\005 \001(\0132\034.mojo.lang.StringLiteralExp" +
      "rH\000\0229\n\021blob_literal_expr\030\006 \001(\0132\034.mojo.db" +
      ".sql.BlobLiteralExprH\000\0226\n\017identifier_exp" +
      "r\030\007 \001(\0132\033.mojo.db.sql.IdentifierExprH\000\022=" +
      "\n\023bind_parameter_expr\030\n \001(\0132\036.mojo.db.sq" +
      "l.BindParameterExprH\000\0225\n\017column_ref_expr" +
      "\030\013 \001(\0132\032.mojo.db.sql.ColumnRefExprH\000\0229\n\021" +
      "prefix_unary_expr\030\017 \001(\0132\034.mojo.db.sql.Pr" +
      "efixUnaryExprH\000\022;\n\022postfix_unary_expr\030\020 " +
      "\001(\0132\035.mojo.db.sql.PostfixUnaryExprH\000\022.\n\013" +
      "binary_expr\030\021 \001(\0132\027.mojo.db.sql.BinaryEx" +
      "prH\000\0220\n\014between_expr\030\022 \001(\0132\030.mojo.db.sql" +
      ".BetweenExprH\000\022&\n\007in_expr\030\023 \001(\0132\023.mojo.d" +
      "b.sql.InExprH\000\022*\n\tcase_expr\030\024 \001(\0132\025.mojo" +
      ".db.sql.CaseExprH\000\022;\n\022function_call_expr" +
      "\030\025 \001(\0132\035.mojo.db.sql.FunctionCallExprH\000\022" +
      "2\n\rsubquery_expr\030\036 \001(\0132\031.mojo.db.sql.Sub" +
      "queryExprH\000B\014\n\nexpression\"\317\001\n\nFromClause" +
      "\022+\n\016start_position\030\001 \001(\0132\023.mojo.lang.Pos" +
      "ition\022)\n\014end_position\030\002 \001(\0132\023.mojo.lang." +
      "Position\022\014\n\004kind\030\004 \001(\003\022\020\n\010implicit\030\005 \001(\010" +
      "\022\"\n\006tables\030\n \003(\0132\022.mojo.db.sql.Table\022%\n\004" +
      "join\030\013 \001(\0132\027.mojo.db.sql.JoinClause\"\265\001\n\r" +
      "GroupByClause\022+\n\016start_position\030\001 \001(\0132\023." +
      "mojo.lang.Position\022)\n\014end_position\030\002 \001(\013" +
      "2\023.mojo.lang.Position\022\014\n\004kind\030\004 \001(\003\022\020\n\010i" +
      "mplicit\030\005 \001(\010\022,\n\013expressions\030\n \003(\0132\027.moj" +
      "o.db.sql.Expression\"\263\001\n\014HavingClause\022+\n\016" +
      "start_position\030\001 \001(\0132\023.mojo.lang.Positio" +
      "n\022)\n\014end_position\030\002 \001(\0132\023.mojo.lang.Posi" +
      "tion\022\014\n\004kind\030\004 \001(\003\022\020\n\010implicit\030\005 \001(\010\022+\n\n" +
      "expression\030\n \001(\0132\027.mojo.db.sql.Expressio" +
      "n\"\241\003\n\nJoinClause\022+\n\016start_position\030\001 \001(\013" +
      "2\023.mojo.lang.Position\022)\n\014end_position\030\002 " +
      "\001(\0132\023.mojo.lang.Position\022\014\n\004kind\030\004 \001(\003\022\020" +
      "\n\010implicit\030\005 \001(\010\022!\n\005table\030\n \001(\0132\022.mojo.d" +
      "b.sql.Table\0222\n\010operator\030\017 \001(\0162 .mojo.db." +
      "sql.JoinClause.Operator\022%\n\004left\030\020 \001(\0132\027." +
      "mojo.db.sql.JoinClause\022&\n\005right\030\021 \001(\0132\027." +
      "mojo.db.sql.JoinClause\0226\n\nconstraint\030\022 \001" +
      "(\0132\".mojo.db.sql.JoinClause.Constraint\032\027" +
      "\n\nConstraint\022\t\n\001v\030\001 \001(\003\"$\n\010Operator\022\030\n\024O" +
      "PERATOR_UNSPECIFIED\020\000\"\231\002\n\013LimitClause\022+\n" +
      "\016start_position\030\001 \001(\0132\023.mojo.lang.Positi" +
      "on\022)\n\014end_position\030\002 \001(\0132\023.mojo.lang.Pos" +
      "ition\022\014\n\004kind\030\004 \001(\003\022\020\n\010implicit\030\005 \001(\010\022%\n" +
      "\004rows\030\n \001(\0132\027.mojo.db.sql.Expression\022-\n\n" +
      "expression\030\013 \001(\0132\027.mojo.db.sql.Expressio" +
      "nH\000\0222\n\roffset_clause\030\014 \001(\0132\031.mojo.db.sql" +
      ".OffsetClauseH\000B\010\n\006offset\"\256\001\n\014OffsetClau" +
      "se\022+\n\016start_position\030\001 \001(\0132\023.mojo.lang.P" +
      "osition\022)\n\014end_position\030\002 \001(\0132\023.mojo.lan" +
      "g.Position\022\014\n\004kind\030\004 \001(\003\022\020\n\010implicit\030\005 \001" +
      "(\010\022&\n\005value\030\n \001(\0132\027.mojo.db.sql.Expressi" +
      "on\"\261\001\n\rOrderByClause\022+\n\016start_position\030\001" +
      " \001(\0132\023.mojo.lang.Position\022)\n\014end_positio" +
      "n\030\002 \001(\0132\023.mojo.lang.Position\022\014\n\004kind\030\004 \001" +
      "(\003\022\020\n\010implicit\030\005 \001(\010\022(\n\torderings\030\n \003(\0132" +
      "\025.mojo.db.sql.Ordering\"\226\001\n\010Ordering\022+\n\ne" +
      "xpression\030\001 \001(\0132\027.mojo.db.sql.Expression" +
      "\022\021\n\tcollation\030\002 \001(\t\022!\n\005order\030\003 \001(\0162\022.moj" +
      "o.db.sql.Order\022\023\n\013nulls_first\030\005 \001(\010\022\022\n\nn" +
      "ulls_last\030\006 \001(\010\"\362\002\n\020PostfixUnaryExpr\022+\n\016" +
      "start_position\030\001 \001(\0132\023.mojo.lang.Positio" +
      "n\022)\n\014end_position\030\002 \001(\0132\023.mojo.lang.Posi" +
      "tion\022\014\n\004kind\030\004 \001(\005\022\020\n\010implicit\030\005 \001(\010\022\027\n\017" +
      "operator_symbol\030\n \001(\t\022)\n\010argument\030\013 \001(\0132" +
      "\027.mojo.db.sql.Expression\0228\n\010operator\030\017 \001" +
      "(\0162&.mojo.db.sql.PostfixUnaryExpr.Operat" +
      "or\"h\n\010Operator\022\030\n\024OPERATOR_UNSPECIFIED\020\000" +
      "\022\024\n\020OPERATOR_IS_NULL\020\001\022\025\n\021OPERATOR_NOT_N" +
      "ULL\020\002\022\025\n\021OPERATOR_EXTENDED\020c\"\247\003\n\017PrefixU" +
      "naryExpr\022+\n\016start_position\030\001 \001(\0132\023.mojo." +
      "lang.Position\022)\n\014end_position\030\002 \001(\0132\023.mo" +
      "jo.lang.Position\022\014\n\004kind\030\004 \001(\005\022\020\n\010implic" +
      "it\030\005 \001(\010\022\027\n\017operator_symbol\030\n \001(\t\022)\n\010arg" +
      "ument\030\013 \001(\0132\027.mojo.db.sql.Expression\0227\n\010" +
      "operator\030\017 \001(\0162%.mojo.db.sql.PrefixUnary" +
      "Expr.Operator\"\236\001\n\010Operator\022\030\n\024OPERATOR_U" +
      "NSPECIFIED\020\000\022\022\n\016OPERATOR_MINUS\020\001\022\021\n\rOPER" +
      "ATOR_PLUS\020\002\022\022\n\016OPERATOR_TILDE\020\003\022\020\n\014OPERA" +
      "TOR_NOT\020\004\022\024\n\020OPERATOR_BIT_NOT\020\005\022\025\n\021OPERA" +
      "TOR_EXTENDED\020c\"\340\001\n\014SelectClause\022+\n\016start" +
      "_position\030\001 \001(\0132\023.mojo.lang.Position\022)\n\014" +
      "end_position\030\002 \001(\0132\023.mojo.lang.Position\022" +
      "\014\n\004kind\030\004 \001(\003\022\020\n\010implicit\030\005 \001(\010\0222\n\nquant" +
      "ifier\030\n \001(\0162\036.mojo.db.sql.DataSetQuantif" +
      "ier\022$\n\007columns\030\014 \003(\0132\023.mojo.db.sql.Colum" +
      "n\"\314\004\n\nSelectStmt\022+\n\016start_position\030\001 \001(\013" +
      "2\023.mojo.lang.Position\022)\n\014end_position\030\002 " +
      "\001(\0132\023.mojo.lang.Position\022\014\n\004kind\030\004 \001(\003\022\020" +
      "\n\010implicit\030\005 \001(\010\022%\n\004with\030\n \001(\0132\027.mojo.db" +
      ".sql.WithClause\0222\n\rselect_clause\030\013 \001(\0132\031" +
      ".mojo.db.sql.SelectClauseH\000\0226\n\017compound_" +
      "select\030\014 \001(\0132\033.mojo.db.sql.CompoundSelec" +
      "tH\000\022)\n\006values\030\r \001(\0132\031.mojo.db.sql.Values" +
      "Clause\022%\n\004from\030\016 \001(\0132\027.mojo.db.sql.FromC" +
      "lause\022\'\n\005where\030\017 \001(\0132\030.mojo.db.sql.Where" +
      "Clause\022,\n\010group_by\030\020 \001(\0132\032.mojo.db.sql.G" +
      "roupByClause\022)\n\006having\030\021 \001(\0132\031.mojo.db.s" +
      "ql.HavingClause\022,\n\010order_by\030\024 \001(\0132\032.mojo" +
      ".db.sql.OrderByClause\022\'\n\005limit\030\025 \001(\0132\030.m" +
      "ojo.db.sql.LimitClauseB\010\n\006select\"\276\001\n\014Sub" +
      "queryExpr\022+\n\016start_position\030\001 \001(\0132\023.mojo" +
      ".lang.Position\022)\n\014end_position\030\002 \001(\0132\023.m" +
      "ojo.lang.Position\022\014\n\004kind\030\004 \001(\005\022\020\n\010impli" +
      "cit\030\005 \001(\010\022\016\n\006exists\030\n \001(\010\022&\n\005query\030\013 \001(\013" +
      "2\027.mojo.db.sql.SelectStmt\"\271\001\n\005Table\0220\n\016t" +
      "able_name_val\030\001 \001(\0132\026.mojo.db.sql.TableN" +
      "ameH\000\022A\n\027table_function_name_val\030\002 \001(\0132\036" +
      ".mojo.db.sql.TableFunctionNameH\000\0222\n\017tabl" +
      "e_query_val\030\003 \001(\0132\027.mojo.db.sql.TableQue" +
      "ryH\000B\007\n\005table\"=\n\tTableName\022\023\n\013schema_nam" +
      "e\030\n \001(\t\022\014\n\004name\030\r \001(\t\022\r\n\005alias\030\017 \001(\t\"q\n\021" +
      "TableFunctionName\022\023\n\013schema_name\030\n \001(\t\022\014" +
      "\n\004name\030\r \001(\t\022*\n\targuments\030\016 \003(\0132\027.mojo.d" +
      "b.sql.Expression\022\r\n\005alias\030\017 \001(\t\"C\n\nTable" +
      "Query\022&\n\005query\030\n \001(\0132\027.mojo.db.sql.Selec" +
      "tStmt\022\r\n\005alias\030\017 \001(\t\"\307\001\n\tUnaryExpr\022+\n\016st" +
      "art_position\030\001 \001(\0132\023.mojo.lang.Position\022" +
      ")\n\014end_position\030\002 \001(\0132\023.mojo.lang.Positi" +
      "on\022\014\n\004kind\030\004 \001(\005\022\020\n\010implicit\030\005 \001(\010\022\027\n\017op" +
      "erator_symbol\030\n \001(\t\022)\n\010argument\030\013 \001(\0132\027." +
      "mojo.db.sql.Expression\"\257\001\n\014ValuesClause\022" +
      "+\n\016start_position\030\001 \001(\0132\023.mojo.lang.Posi" +
      "tion\022)\n\014end_position\030\002 \001(\0132\023.mojo.lang.P" +
      "osition\022\014\n\004kind\030\004 \001(\003\022\020\n\010implicit\030\005 \001(\010\022" +
      "\'\n\006values\030\n \003(\0132\027.mojo.db.sql.Expression" +
      "\"\262\001\n\013WhereClause\022+\n\016start_position\030\001 \001(\013" +
      "2\023.mojo.lang.Position\022)\n\014end_position\030\002 " +
      "\001(\0132\023.mojo.lang.Position\022\014\n\004kind\030\004 \001(\003\022\020" +
      "\n\010implicit\030\005 \001(\010\022+\n\nexpression\030\n \001(\0132\027.m" +
      "ojo.db.sql.Expression\"Z\n\016TemporaryTable\022" +
      "\014\n\004name\030\001 \001(\t\022\017\n\007columns\030\002 \003(\t\022)\n\010subque" +
      "ry\030\003 \001(\0132\027.mojo.db.sql.SelectStmt\"\304\001\n\nWi" +
      "thClause\022+\n\016start_position\030\001 \001(\0132\023.mojo." +
      "lang.Position\022)\n\014end_position\030\002 \001(\0132\023.mo" +
      "jo.lang.Position\022\014\n\004kind\030\004 \001(\003\022\020\n\010implic" +
      "it\030\005 \001(\010\022+\n\006tables\030\n \003(\0132\033.mojo.db.sql.T" +
      "emporaryTable\022\021\n\trecursive\030\017 \001(\010BW\n\031org." +
      "mojo-lang.mojo.db.sqlB\010SqlProtoP\001Z.githu" +
      "b.com/mojo-lang/db/go/pkg/mojo/db/sql;sq" +
      "lb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojo-lang.mojo.db.sql.BetweenExprProto.getDescriptor(),
          org.mojo-lang.mojo.db.sql.BindParameterExprProto.getDescriptor(),
          org.mojo-lang.mojo.db.sql.BlobLiteralExprProto.getDescriptor(),
          org.mojo-lang.mojo.db.sql.CaseExprProto.getDescriptor(),
          org.mojo-lang.mojo.db.sql.ClauseProto.getDescriptor(),
          org.mojo-lang.mojo.db.sql.ColumnRefExprProto.getDescriptor(),
          org.mojo-lang.mojo.db.sql.DataManipulationStmtProto.getDescriptor(),
          org.mojo-lang.mojo.db.sql.DataSetQuantifierProto.getDescriptor(),
          org.mojo-lang.mojo.db.sql.FunctionCallExprProto.getDescriptor(),
          org.mojo-lang.mojo.db.sql.IdentifierExprProto.getDescriptor(),
          org.mojo-lang.mojo.db.sql.InExprProto.getDescriptor(),
          org.mojo-lang.mojo.db.sql.OrderProto.getDescriptor(),
          org.mojolang.mojo.lang.LangProto.getDescriptor(),
        });
    internal_static_mojo_db_sql_BinaryExpr_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_db_sql_BinaryExpr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_BinaryExpr_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Operator", "OperatorSymbol", "OperatorPrecedence", "LeftArgument", "RightArgument", });
    internal_static_mojo_db_sql_Column_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mojo_db_sql_Column_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_Column_descriptor,
        new java.lang.String[] { "AllColumnVal", "DerivedColumnVal", "Column", });
    internal_static_mojo_db_sql_AllColumn_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mojo_db_sql_AllColumn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_AllColumn_descriptor,
        new java.lang.String[] { "TableName", });
    internal_static_mojo_db_sql_DerivedColumn_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_mojo_db_sql_DerivedColumn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_DerivedColumn_descriptor,
        new java.lang.String[] { "Expr", "As", });
    internal_static_mojo_db_sql_CompoundSelect_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_mojo_db_sql_CompoundSelect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_CompoundSelect_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "With", "SelectClause", "CompoundSelect", "Values", "From", "Where", "GroupBy", "Having", "OrderBy", "Limit", "Operator", "Left", "Right", "Select", });
    internal_static_mojo_db_sql_Expression_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_mojo_db_sql_Expression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_Expression_descriptor,
        new java.lang.String[] { "NullLiteralExpr", "BoolLiteralExpr", "IntegerLiteralExpr", "FloatLiteralExpr", "StringLiteralExpr", "BlobLiteralExpr", "IdentifierExpr", "BindParameterExpr", "ColumnRefExpr", "PrefixUnaryExpr", "PostfixUnaryExpr", "BinaryExpr", "BetweenExpr", "InExpr", "CaseExpr", "FunctionCallExpr", "SubqueryExpr", "Expression", });
    internal_static_mojo_db_sql_FromClause_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_mojo_db_sql_FromClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_FromClause_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Tables", "Join", });
    internal_static_mojo_db_sql_GroupByClause_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_mojo_db_sql_GroupByClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_GroupByClause_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Expressions", });
    internal_static_mojo_db_sql_HavingClause_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_mojo_db_sql_HavingClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_HavingClause_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Expression", });
    internal_static_mojo_db_sql_JoinClause_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_mojo_db_sql_JoinClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_JoinClause_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Table", "Operator", "Left", "Right", "Constraint", });
    internal_static_mojo_db_sql_JoinClause_Constraint_descriptor =
      internal_static_mojo_db_sql_JoinClause_descriptor.getNestedTypes().get(0);
    internal_static_mojo_db_sql_JoinClause_Constraint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_JoinClause_Constraint_descriptor,
        new java.lang.String[] { "V", });
    internal_static_mojo_db_sql_LimitClause_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_mojo_db_sql_LimitClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_LimitClause_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Rows", "Expression", "OffsetClause", "Offset", });
    internal_static_mojo_db_sql_OffsetClause_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_mojo_db_sql_OffsetClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_OffsetClause_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Value", });
    internal_static_mojo_db_sql_OrderByClause_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_mojo_db_sql_OrderByClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_OrderByClause_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Orderings", });
    internal_static_mojo_db_sql_Ordering_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_mojo_db_sql_Ordering_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_Ordering_descriptor,
        new java.lang.String[] { "Expression", "Collation", "Order", "NullsFirst", "NullsLast", });
    internal_static_mojo_db_sql_PostfixUnaryExpr_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_mojo_db_sql_PostfixUnaryExpr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_PostfixUnaryExpr_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "OperatorSymbol", "Argument", "Operator", });
    internal_static_mojo_db_sql_PrefixUnaryExpr_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_mojo_db_sql_PrefixUnaryExpr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_PrefixUnaryExpr_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "OperatorSymbol", "Argument", "Operator", });
    internal_static_mojo_db_sql_SelectClause_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_mojo_db_sql_SelectClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_SelectClause_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Quantifier", "Columns", });
    internal_static_mojo_db_sql_SelectStmt_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_mojo_db_sql_SelectStmt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_SelectStmt_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "With", "SelectClause", "CompoundSelect", "Values", "From", "Where", "GroupBy", "Having", "OrderBy", "Limit", "Select", });
    internal_static_mojo_db_sql_SubqueryExpr_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_mojo_db_sql_SubqueryExpr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_SubqueryExpr_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Exists", "Query", });
    internal_static_mojo_db_sql_Table_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_mojo_db_sql_Table_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_Table_descriptor,
        new java.lang.String[] { "TableNameVal", "TableFunctionNameVal", "TableQueryVal", "Table", });
    internal_static_mojo_db_sql_TableName_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_mojo_db_sql_TableName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_TableName_descriptor,
        new java.lang.String[] { "SchemaName", "Name", "Alias", });
    internal_static_mojo_db_sql_TableFunctionName_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_mojo_db_sql_TableFunctionName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_TableFunctionName_descriptor,
        new java.lang.String[] { "SchemaName", "Name", "Arguments", "Alias", });
    internal_static_mojo_db_sql_TableQuery_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_mojo_db_sql_TableQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_TableQuery_descriptor,
        new java.lang.String[] { "Query", "Alias", });
    internal_static_mojo_db_sql_UnaryExpr_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_mojo_db_sql_UnaryExpr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_UnaryExpr_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "OperatorSymbol", "Argument", });
    internal_static_mojo_db_sql_ValuesClause_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_mojo_db_sql_ValuesClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_ValuesClause_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Values", });
    internal_static_mojo_db_sql_WhereClause_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_mojo_db_sql_WhereClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_WhereClause_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Expression", });
    internal_static_mojo_db_sql_TemporaryTable_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_mojo_db_sql_TemporaryTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_TemporaryTable_descriptor,
        new java.lang.String[] { "Name", "Columns", "Subquery", });
    internal_static_mojo_db_sql_WithClause_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_mojo_db_sql_WithClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_WithClause_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Tables", "Recursive", });
    org.mojo-lang.mojo.db.sql.BetweenExprProto.getDescriptor();
    org.mojo-lang.mojo.db.sql.BindParameterExprProto.getDescriptor();
    org.mojo-lang.mojo.db.sql.BlobLiteralExprProto.getDescriptor();
    org.mojo-lang.mojo.db.sql.CaseExprProto.getDescriptor();
    org.mojo-lang.mojo.db.sql.ClauseProto.getDescriptor();
    org.mojo-lang.mojo.db.sql.ColumnRefExprProto.getDescriptor();
    org.mojo-lang.mojo.db.sql.DataManipulationStmtProto.getDescriptor();
    org.mojo-lang.mojo.db.sql.DataSetQuantifierProto.getDescriptor();
    org.mojo-lang.mojo.db.sql.FunctionCallExprProto.getDescriptor();
    org.mojo-lang.mojo.db.sql.IdentifierExprProto.getDescriptor();
    org.mojo-lang.mojo.db.sql.InExprProto.getDescriptor();
    org.mojo-lang.mojo.db.sql.OrderProto.getDescriptor();
    org.mojolang.mojo.lang.LangProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
