// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/sql/set_clause.proto

package org.mojo-lang.mojo.db.sql;

public interface UpdateItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.db.sql.UpdateItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string column_name = 1;</code>
   * @return The columnName.
   */
  java.lang.String getColumnName();
  /**
   * <code>string column_name = 1;</code>
   * @return The bytes for columnName.
   */
  com.google.protobuf.ByteString
      getColumnNameBytes();

  /**
   * <code>.mojo.db.sql.Expression value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.mojo.db.sql.Expression value = 2;</code>
   * @return The value.
   */
  org.mojo-lang.mojo.db.sql.Expression getValue();
  /**
   * <code>.mojo.db.sql.Expression value = 2;</code>
   */
  org.mojo-lang.mojo.db.sql.ExpressionOrBuilder getValueOrBuilder();
}
