// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/sql/update_stmt.proto

package org.mojo-lang.mojo.db.sql;

public interface UpdateStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.db.sql.UpdateStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return Whether the startPosition field is set.
   */
  boolean hasStartPosition();
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return The startPosition.
   */
  org.mojolang.mojo.lang.Position getStartPosition();
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder();

  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return Whether the endPosition field is set.
   */
  boolean hasEndPosition();
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return The endPosition.
   */
  org.mojolang.mojo.lang.Position getEndPosition();
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder();

  /**
   * <code>int64 kind = 4;</code>
   * @return The kind.
   */
  long getKind();

  /**
   * <code>bool implicit = 5;</code>
   * @return The implicit.
   */
  boolean getImplicit();

  /**
   * <code>.mojo.db.sql.WithClause with = 10;</code>
   * @return Whether the with field is set.
   */
  boolean hasWith();
  /**
   * <code>.mojo.db.sql.WithClause with = 10;</code>
   * @return The with.
   */
  org.mojo-lang.mojo.db.sql.WithClause getWith();
  /**
   * <code>.mojo.db.sql.WithClause with = 10;</code>
   */
  org.mojo-lang.mojo.db.sql.WithClauseOrBuilder getWithOrBuilder();

  /**
   * <code>.mojo.db.sql.UpdateClause update = 11;</code>
   * @return Whether the update field is set.
   */
  boolean hasUpdate();
  /**
   * <code>.mojo.db.sql.UpdateClause update = 11;</code>
   * @return The update.
   */
  org.mojo-lang.mojo.db.sql.UpdateClause getUpdate();
  /**
   * <code>.mojo.db.sql.UpdateClause update = 11;</code>
   */
  org.mojo-lang.mojo.db.sql.UpdateClauseOrBuilder getUpdateOrBuilder();

  /**
   * <code>.mojo.db.sql.SetClause set = 12;</code>
   * @return Whether the set field is set.
   */
  boolean hasSet();
  /**
   * <code>.mojo.db.sql.SetClause set = 12;</code>
   * @return The set.
   */
  org.mojo-lang.mojo.db.sql.SetClause getSet();
  /**
   * <code>.mojo.db.sql.SetClause set = 12;</code>
   */
  org.mojo-lang.mojo.db.sql.SetClauseOrBuilder getSetOrBuilder();

  /**
   * <code>.mojo.db.sql.FromClause from = 13;</code>
   * @return Whether the from field is set.
   */
  boolean hasFrom();
  /**
   * <code>.mojo.db.sql.FromClause from = 13;</code>
   * @return The from.
   */
  org.mojo-lang.mojo.db.sql.FromClause getFrom();
  /**
   * <code>.mojo.db.sql.FromClause from = 13;</code>
   */
  org.mojo-lang.mojo.db.sql.FromClauseOrBuilder getFromOrBuilder();

  /**
   * <code>.mojo.db.sql.WhereClause where = 14;</code>
   * @return Whether the where field is set.
   */
  boolean hasWhere();
  /**
   * <code>.mojo.db.sql.WhereClause where = 14;</code>
   * @return The where.
   */
  org.mojo-lang.mojo.db.sql.WhereClause getWhere();
  /**
   * <code>.mojo.db.sql.WhereClause where = 14;</code>
   */
  org.mojo-lang.mojo.db.sql.WhereClauseOrBuilder getWhereOrBuilder();

  /**
   * <code>.mojo.db.sql.ReturningClause returning = 15;</code>
   * @return Whether the returning field is set.
   */
  boolean hasReturning();
  /**
   * <code>.mojo.db.sql.ReturningClause returning = 15;</code>
   * @return The returning.
   */
  org.mojo-lang.mojo.db.sql.ReturningClause getReturning();
  /**
   * <code>.mojo.db.sql.ReturningClause returning = 15;</code>
   */
  org.mojo-lang.mojo.db.sql.ReturningClauseOrBuilder getReturningOrBuilder();
}
