// Code generated by mojo. DO NOT EDIT.
// Rerunning mojo will overwrite this file.
//
// Copyright 2021 Mojo-lang.org
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sql

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/mojo-lang/core/go/pkg/mojo/core"
)

var PostfixUnaryExprOperatorNames = map[int32]string{
	0:  "unspecified",
	1:  "is_null",
	2:  "not_null",
	99: "extended",
}

var PostfixUnaryExprOperatorValues = map[string]PostfixUnaryExpr_Operator{
	"unspecified": PostfixUnaryExpr_OPERATOR_UNSPECIFIED,
	"is_null":     PostfixUnaryExpr_OPERATOR_IS_NULL,
	"not_null":    PostfixUnaryExpr_OPERATOR_NOT_NULL,
	"extended":    PostfixUnaryExpr_OPERATOR_EXTENDED,
}

func (x PostfixUnaryExpr_Operator) Format() string {
	v := int32(x)
	if s, ok := PostfixUnaryExprOperatorNames[v]; ok {
		if v == 0 && "unspecified" == strings.ToLower(s) {
			return ""
		}
		return s
	}
	if v == 0 {
		return ""
	}
	return strconv.Itoa(int(v))
}

func (x PostfixUnaryExpr_Operator) ToString() string {
	return x.Format()
}

func (x *PostfixUnaryExpr_Operator) Parse(value string) error {
	if x != nil && len(value) > 0 {
		if s, ok := PostfixUnaryExprOperatorValues[value]; ok {
			*x = s
		} else {
			v := core.CaseStyler("snake")(value)
			if s, ok = PostfixUnaryExprOperatorValues[v]; ok {
				*x = s
			} else {
				return fmt.Errorf("invalid PostfixUnaryExpr_Operator: %s", value)
			}
		}
	}
	return nil
}

func ParsePostfixUnaryExpr_Operator(value string) (PostfixUnaryExpr_Operator, error) {
	var v PostfixUnaryExpr_Operator
	if err := (&v).Parse(value); err != nil {
		return v, err
	}
	return v, nil
}
